### ISSUE TITLE
weird null exception error

### ISSUE THREAD

**Issue by JacobJohansen** [mrniko/redisson#113]
I was wondering if anyone else has seen this and what the cause would be(threading?)
``` Java
java.lang.NullPointerException: null
	at org.redisson.RedissonList.size(RedissonList.java:53) ~[redisson-1.2.0.jar:na]
	at org.redisson.RedissonList.isEmpty(RedissonList.java:63) ~[redisson-1.2.0.jar:na]
	at org.redisson.RedissonQueue.peek(RedissonQueue.java:89) ~[redisson-1.2.0.jar:na]
```

**Comment by JacobJohansen** [comment]
connection issue with pool set up, Solved
