### ISSUE TITLE
ClassCastException in RedissonCountDownLatch.trySetCount

### ISSUE THREAD

**Issue by zkiss** [mrniko/redisson#116]
Take a nice and clean redis server.

Execute the following code twice
```
public class RedissonTest {

	public static void main(String[] args) {
		Redisson redisson = Redisson.create();

		RCountDownLatch latch = redisson.getCountDownLatch("testlatch");
		latch.trySetCount(10);
		latch.countDown();

		// latch.delete();
		redisson.shutdown();
	}

}
```

At the second execution you get a ClassCastException

```
13:51:53.280 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
13:51:53.286 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetectionLevel: simple
13:51:53.293 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
13:51:53.294 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
13:51:53.294 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
13:51:53.294 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
13:51:53.295 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
13:51:53.295 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
13:51:53.295 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
13:51:53.295 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
13:51:53.296 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
13:51:53.296 [main] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
13:51:53.296 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
13:51:53.296 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
13:51:53.296 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
13:51:53.305 [main] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
13:51:53.318 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
13:51:53.318 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
13:51:53.353 [main] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x7680cb61c5330bfa (took 0 ms)
13:51:53.369 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
13:51:53.370 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
13:51:53.420 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
13:51:53.429 [nioEventLoopGroup-2-1] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at org.redisson.RedissonCountDownLatch$4.execute(RedissonCountDownLatch.java:252)
	at org.redisson.RedissonCountDownLatch$4.execute(RedissonCountDownLatch.java:247)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:272)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:261)
	at org.redisson.RedissonCountDownLatch.trySetCount(RedissonCountDownLatch.java:247)
	at test.RedissonTest.main(RedissonTest.java:12)
```

And the redis monitor output is
```
1422020603.147820 [0 127.0.0.1:46751] "WATCH" "testlatch"
1422020603.151582 [0 127.0.0.1:46751] "GET" "testlatch"
1422020603.152111 [0 127.0.0.1:46751] "MULTI"
1422020603.181469 [0 127.0.0.1:46751] "SET" "testlatch" "10"
1422020603.181493 [0 127.0.0.1:46751] "PUBLISH" "redisson_countdownlatch_{testlatch}" "1"
1422020603.181509 [0 127.0.0.1:46751] "EXEC"
1422020603.183029 [0 127.0.0.1:46751] "GET" "testlatch"
1422020603.218605 [0 127.0.0.1:46751] "DECR" "testlatch"

1422020615.069218 [0 127.0.0.1:46752] "WATCH" "testlatch"
1422020615.075969 [0 127.0.0.1:46752] "GET" "testlatch"
```

Running on Java 8

**Comment by mrniko** [comment]
fixed
