### ISSUE TITLE
java.lang.ClassCastException  java.lang.Integer cannot be cast to org.redisson.RedissonLock$LockValue

### ISSUE THREAD

**Issue by bbrui** [mrniko/redisson#118]
when use lock,but throw some class cast exception,sample code :
import java.util.concurrent.locks.Lock;
import org.redisson.Config;
import org.redisson.Redisson;
import org.redisson.connection.RandomLoadBalancer;
import org.redisson.core.RBucket;
public class RedissonLockTest {
	public static void main(String[] args) {
		RedissonLockTest test=new RedissonLockTest();
		test.test2();
	}
	public  void test1(){
		Config config = new Config();
	    config.useSingleServer()
	          .setAddress("127.0.0.1:6379");
		Redisson redisson = Redisson.create(config);
		 Lock lock = redisson.getLock("lock");
        lock.lock();
        RBucket<Integer> bucket= redisson.getBucket("amount");
        bucket.set(100);
        lock.unlock();
        redisson.shutdown();
	}
	
}

error stack:

Exception in thread "main" java.lang.ClassCastException: java.lang.Integer cannot be cast to org.redisson.RedissonLock$LockValue
	at org.redisson.RedissonLock$2.execute(RedissonLock.java:293)
	at org.redisson.RedissonLock$2.execute(RedissonLock.java:1)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:272)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:261)
	at org.redisson.RedissonLock.tryLockInner(RedissonLock.java:286)
	at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:243)
	at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:234)
	at org.redisson.RedissonLock.lock(RedissonLock.java:214)
	at com.tydic.billing.business.experiment.RedissonLockTest.test1(RedissonLockTest.java:21)
	at com.tydic.billing.business.experiment.RedissonLockTest.main(RedissonLockTest.java:13)

**Comment by bbrui** [comment]
I solved a problem by myself.  
redisson.getLock("lock");           the parameter of getLock   need not  exist  in redis.
