### ISSUE TITLE
IllegalArgumentException when hostname is the local loop back in IPv6 format "::1"

### ISSUE THREAD

**Issue by jackygurui** [mrniko/redisson#121]
When the connection returns a master address that is the local loop back in IPv6 format, meaning "::1", it causes the following exception:
java.lang.IllegalArgumentException: hostname can't be null
at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:149)
at java.net.InetSocketAddress.(InetSocketAddress.java:216)
at com.lambdaworks.redis.RedisClient.(RedisClient.java:64)
at org.redisson.connection.MasterSlaveEntry.(MasterSlaveEntry.java:63)
at org.redisson.connection.MasterSlaveConnectionManager.init(MasterSlaveConnectionManager.java:96)

As per http://download.java.net/jdk7/archive/b123/docs/api/java/net/URI.html#URI(java.lang.String) states:
IPv6 addresses are permitted for the host component. An IPv6 address must be enclosed in square brackets ('[' and ']') as specified by RFC 2732.

**Comment by mrniko** [comment]
fixed

**Comment by jackygurui** [comment]
Nice one. Thanks.
