### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by alexbeletsky** [mrniko/redisson#124]
I am testing redisson library with the situation when redis server is down at some point. 

The scenario is:
1. Redis server is up
2. My java app initialises the connection with redis server properly
3. Redis server goes down
4. Java app wants to read an example key from redis
5. After aprox 4 mins I have timeout exception which is completely fine:

```
com.lambdaworks.redis.RedisTimeoutException
at org.redisson.connection.MasterSlaveConnectionManager.readAsync(MasterSlaveConnectionManager.java:359)
	at org.redisson.connection.MasterSlaveConnectionManager.access$100(MasterSlaveConnectionManager.java:62)
	at org.redisson.connection.MasterSlaveConnectionManager$5.run(MasterSlaveConnectionManager.java:350)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:531)
	at io.netty.util.HashedWheelTimer$Worker.notifyExpiredTimeouts(HashedWheelTimer.java:425)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:376)
	at java.lang.Thread.run(Thread.java:744)
```

My question is: How can I change the timeout? Waiting 4 minutes is definitely too long in my case.
I am using SingleServerConfig and what I tried is following (500ms) but this doesnt seem to work: 

```java
    public Redisson redisson() {
    	Config config = new Config();
    	config.setCodec(new DriverStringToJsonCodec());
        config.useSingleServer().setAddress(REDIS_CACHE_URL);
        config.useSingleServer().setRetryAttempts(1);
        config.useSingleServer().setRetryInterval(500);
        return Redisson.create(config);
    }
```

**Comment by alexbeletsky** [comment]
Ok, just found #123 regarding almost same problem. Closing this one.
