### ISSUE TITLE
Java Redisson on single server

### ISSUE THREAD

**Issue by PashaTurok** [mrniko/redisson#129]
I am trying to understan how redisson lib works with redis on my single server. I've downloaded redis, started it and can to the following:

 ./redis-cli
127.0.0.1:6379> get mykey
"somevalue"

Then I've installed in my javaee osgi application redisson and its libs. However, I can't understand how to get my "mykey". The connection I create this way:

Config config = new Config();
config.useSingleServer()
  .setAddress("127.0.0.1:6379")
  .setConnectionPoolSize(10);
Redisson redisson = Redisson.create(config);
 //how to get "mykey"?
redisson.shutdown();
Please, help me.

**Comment by mrniko** [comment]
> //how to get "mykey"?
redisson.getBucket("mykey").get();
or 
redisson.getBucket("mykey").getAsync();

**Comment by PashaTurok** [comment]
Thank you for quick reply.

I did this way:
Redisson redisson = Redisson.create(config);
System.out.println("Test:"+redisson.getBucket("mykey").get());
redisson.shutdown();
But I get the following:

  An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'somevalue': was expecting ('true', 'false' or 'null')
 at [Source: [B@2576bce8; line: 1, column: 23]
    at org.redisson.codec.JsonJacksonCodec.decode(JsonJacksonCodec.java:109)
    at org.redisson.codec.JsonJacksonCodec.decodeValue(JsonJacksonCodec.java:102)
    at org.redisson.codec.RedisCodecWrapper.decodeValue(RedisCodecWrapper.java:42)
    at com.lambdaworks.redis.output.ValueOutput.set(ValueOutput.java:24)
    at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:112)
    at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:72)
    at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:52)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'somevalue': was expecting ('true', 'false' or 'null')
 at [Source: [B@2576bce8; line: 1, column: 23]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
    at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2240)
    at org.redisson.codec.JsonJacksonCodec.decode(JsonJacksonCodec.java:107)
    ... 20 more
]]

**Comment by mrniko** [comment]
it should a json value

**Comment by PashaTurok** [comment]
Ok. Thank you.
