### ISSUE TITLE
lock.lock(2, TimeUnit.SECONDS) report error ERR wrong number of arguments for 'set' command

### ISSUE THREAD

**Issue by gitriver** [mrniko/redisson#156]
RLock lock = redisson.getLock("anyLock");
lock.lock(2, TimeUnit.SECONDS);
lock.unlock();

run it ,report error:
Exception in thread "main" com.lambdaworks.redis.RedisException: ERR wrong number of arguments for 'set' command
at com.lambdaworks.redis.protocol.Command.complete(Command.java:76)
at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:77)
at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:52)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
at java.lang.Thread.run(Thread.java:744)

**Comment by gitriver** [comment]
version is 1.2.0

**Comment by freevest** [comment]
Your redis version may be too low to support SET with timeout, try to use a higher version of redis

**Comment by mrniko** [comment]
i agree, please update your Redis server to 2.8 at least
