### ISSUE TITLE
No enum const class org.redisson.connection.ClusterNodeInfo$Flag.HANDSHAKE

### ISSUE THREAD

**Issue by carlvine500** [mrniko/redisson#159]
redis version: redis-3.0.0
./src/redis-cli -c -p 7001 cluster nodes
-------------------------------------------------------------------------------------------------------------------------
9d97b7a1ee8cc52446a234f7f721e144aceacde3 10.126.53.98:7001 myself,slave a9b71c24f6dc8dca99969f82762904eef69947a9 0 0 2 connected
a9b71c24f6dc8dca99969f82762904eef69947a9 10.126.53.98:7004 master - 0 1431933896610 10 connected 5461-10922
0f92aa118812a4d9f96a1e41ae81ca34313d929f 10.126.53.98:7003 slave 9dd564ac496ebb8ac68af0b2268892debd643b86 0 1431933897111 9 connected
a112df8ccae1f29a1906d6e4f3ae94c92066a507 10.126.53.98:7002 master - 0 1431933895104 3 connected 10923-16383
8099cffcd53498ca95a17bef552ee58e09f969a0 127.0.0.1:7100 handshake - 1431933893297 0 0 disconnected
9dd564ac496ebb8ac68af0b2268892debd643b86 10.126.53.98:7000 master - 0 1431933897111 7 connected 0-5460
7ad08971115b10af5e3e0324582ce7e3ea361ffa 10.126.53.98:7005 slave a112df8ccae1f29a1906d6e4f3ae94c92066a507 0 1431933896109 8 connected
f333c6ead44fe826b1e1f9b019244e1740a47fba 10.126.53.98:7100 master,fail - 1431933882171 1431933881184 0 disconnected
-------------------------------------------------------------------------------------------------------------------------

when redisson was created : 

Exception in thread "main" java.lang.IllegalArgumentException: No enum const class org.redisson.connection.ClusterNodeInfo$Flag.HANDSHAKE
	at java.lang.Enum.valueOf(Enum.java:196)
	at org.redisson.connection.ClusterNodeInfo$Flag.valueOf(ClusterNodeInfo.java:1)
	at org.redisson.connection.ClusterConnectionManager.parse(ClusterConnectionManager.java:246)
	at org.redisson.connection.ClusterConnectionManager.extractPartitions(ClusterConnectionManager.java:188)
	at org.redisson.connection.ClusterConnectionManager.<init>(ClusterConnectionManager.java:62)
	at org.redisson.Redisson.<init>(Redisson.java:53)
	at org.redisson.Redisson.create(Redisson.java:80)
	at com.lambdaworks.redis.ClusterTest.main(ClusterTest.java:29)

**Comment by mrniko** [comment]
fixed
