### ISSUE TITLE
[BUG]Thread dead lock when using distributed lock on 1.2.1

### ISSUE THREAD

**Issue by freevest** [mrniko/redisson#162]
I run into a thread dead lock problem when using distributed lock on 1.2.1:

public static CryptorInstance getCryptorInstanceFromCluster(Redisson redisson) throws NoAvailableCyrptorException
{
	boolean successGetFlag = false;
	CryptorInstance returnInstance = null;

	RLock portLock = null;
	try
	{
		portLock = DAO_Redisson.redisson.getLock(CryptorMessageConstant.DISTRIBUTED_LOCK_CRYPTOR_SELECTOR_NAME);
 portLock.lock(CryptorMessageConstant.DISTRIBUTED_LOCK_CRYPTOR_SELECTOR_TIMEOUT, TimeUnit.SECONDS);

       //Do other work

	}
	catch (NoAvailableCyrptorException ex)
	{
		throw new NoAvailableCyrptorException();
	}
	catch (Exception ex)
	{
		logger.error(ex, ex.fillInStackTrace());
	}
	finally
	{
		if (portLock != null)
			portLock.unlock();
	}

	return returnInstance;
}

There are 10 ten thread call this function:
public class MinaExecutorCallable implements Callable<Object>
{
	@Override
	public Object call() throws Exception
	{
		try
		{
			while (!Thread.interrupted())
			{
				this.tmaInstance.cryptorInstance = CryptorSelector.getCryptorInstanceFromCluster(DAO_Redisson.redisson);
				
				
			}
		}
		catch (InterruptedException ex)
		{
			logger.warn("InterruptedException");
		}

		return null;
	}
}

After a certain period, some threads will be dead lock, and we can tell this by VisualVM's thread dump:

"pool-1-thread-12" #29 prio=5 os_prio=0 tid=0x16050800 nid=0x121c waiting on condition [0x1786f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0b462068> (a java.util.concurrent.Semaphore$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(Unknown Source)
	at java.util.concurrent.Semaphore.acquire(Unknown Source)
	at org.redisson.RedissonLock.lockInterruptibly(RedissonLock.java:269)
	at org.redisson.RedissonLock.lock(RedissonLock.java:224)
	at com.xxxxxx.xxxx.xxx.cryptor.CryptorSelector.getCryptorInstanceFromCluster(CryptorSelector.java:33)
	at com.xxxx.xxxx.xxxxx.xxxxx(xxxxxx.java:150)
	at com.xxxxx.xxxx.xxxx.executor.MinaExecutorCallable.call(MinaExecutorCallable.java:116)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
	- <0x0a7568a8> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by freevest** [comment]
![Uploading QQ图片20150518211336.jpg…]()
As you can see, 9 of 10 thread have long been into a 'WAIT' status.

**Comment by mrniko** [comment]
could write a test for this?
