### ISSUE TITLE
KryoCodec strange behaviour

### ISSUE THREAD

**Issue by Gladmir** [mrniko/redisson#166]
Between client restarts, KyroCodec serialisation randomly fails with exception;

com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 46
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119)
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:666)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:777)
	at org.redisson.codec.KryoCodec.decode(KryoCodec.java:92)
	at org.redisson.codec.KryoCodec.decodeValue(KryoCodec.java:140)
	at org.redisson.codec.RedisCodecWrapper.decodeValue(RedisCodecWrapper.java:42)
	at com.lambdaworks.redis.output.MapScanOutput.set(MapScanOutput.java:19)
	at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:112)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:71)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

Prior to release this feature, did you run some regression tests for it? Also do you have any comment about the exception?

P.S: Content of the redis and the classes are same between restarts and I am simply applying Predicate upon RMap.

Edit: Between restarts, Kyro is sweeping the classes and give them uniqueIds in order to identify and serialise/deserialise them. I used to give Kyro exact list of classes in the exact order but with the auto discovery I think class loading order causes this issue right now. 

IMHO, best solution would be to provide an interface for registering the Kyro classes to the underlying KyroCodec impl.

**Comment by mrniko** [comment]
Now you may declare classes list as argument in KryoCodec constructor. Please check is it enough for you

**Comment by Gladmir** [comment]
@mrniko Thanks, random class loading issue is no more problem with this enhancement.
