### ISSUE TITLE
Issue in locking on key in concurrency

### ISSUE THREAD

**Issue by savanpatel** [mrniko/redisson#171]
In my project, I have a servlet, that call a utility class.
Utility class calls a wrapper class that  I have implemented over redisson lock.
Wrapper class holds RLock object for a thread and provides lock and unlock methods that call RLock's lock and unlock method
But while running a apache ab-test tool for concurrency, Following exception occurs.
Can you tell me if I am missing something over here?

java.lang.IllegalMonitorStateException: Attempt to unlock lock, not locked by current id: 286dad3d-dd4b-434e-bca7-30c35eec01eb thread-id: 158
	at org.redisson.RedissonLock$4.execute(RedissonLock.java:416)
	at org.redisson.RedissonLock$4.execute(RedissonLock.java:1)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:272)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:261)
	at org.redisson.RedissonLock.unlock(RedissonLock.java:402)
	at com.sokrati.redisClient.JedisConnection.unlock(JedisConnection.java:431)
	at com.sokrati.throttlingService.operations.RedisOperations.unlock(RedisOperations.java:112)
	at com.sokrati.throttlingService.utils.ThrottlerUtil.checkKeyBlocked(ThrottlerUtil.java:135)
	at com.sokrati.throttlingService.servlets.Throttler.fetch(Throttler.java:70)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sokrati.restCommunicator.RestCommunicator.invokeServiceMethod(RestCommunicator.java:308)

**Comment by mrniko** [comment]
hi!

you should unlock the lock in the same thread it has been locked

**Comment by savanpatel** [comment]
I am unloking thread from same thread still the same exception happens

**Comment by Gladmir** [comment]
Would you mind sharing the code snippet where you lock and unlock ?

**Comment by savanpatel** [comment]
public static BlockageDetails checkKeyBlocked(String key,
                                                  RedisConnection rc)
        throws UnableToGetConnection, UnableToGetCredentials
    {
        BlockageDetails blockageDetails = new BlockageDetails(key, 0L);
        BaseOperations baseOperations = BaseOperations.getInstance(rc);
        String blockKey = getBlockKey(key);

        Locker lock = baseOperations.lock(ThrottlerUtil.getLockKey(key));
        if (baseOperations.isExists(blockKey))
        {
            String expiryTime = baseOperations.getValue(blockKey);
            if(Long.parseLong(expiryTime) > new Date().getTime())
            {
                blockageDetails =
                    new BlockageDetails(
                        key,
                        baseOperations.getRemainingTime(blockKey)
                    );
            }
        }
        baseOperations.unlock(lock);
        baseOperations.disconnect();
        return blockageDetails;
    }



this is function that my servlet calls

**Comment by savanpatel** [comment]
public static BlockageDetails checkKeyBlocked(String key,
                                                  RedisConnection rc)
        throws UnableToGetConnection, UnableToGetCredentials
    {
        BlockageDetails blockageDetails = new BlockageDetails(key, 0L);
        BaseOperations baseOperations = BaseOperations.getInstance(rc);
        String blockKey = getBlockKey(key);
    
        Locker lock = baseOperations.lock(ThrottlerUtil.getLockKey(key));
        if (baseOperations.isExists(blockKey))
        {
            String expiryTime = baseOperations.getValue(blockKey);
            if(Long.parseLong(expiryTime) > new Date().getTime())
            {
                blockageDetails = 
                    new BlockageDetails(
                        key,
                        baseOperations.getRemainingTime(blockKey)
                    );
            }
        }
        baseOperations.unlock(lock);
        baseOperations.disconnect();
        return blockageDetails;
    }



this is function that my servlet calls

**Comment by Gladmir** [comment]
Since I can't see the related underlying implementation of yours, my wild guess would be; You have a possible race condition with your getBlockKey and/or ThrottlerUtil.getLockKey method accessors. 

Are those synchronised ? Are you sure that you are generating/returning correct keys per Servlet (per Servlet Container Thread) request?

You can easily debug it via checking the thread id just before and after you acquired the lock and also compare the ids with your RLock wrapper object.

RLock object is being serialised to Redis with a JVM wide unique UUID and thread id, you can make double check with Redis also (if you are using default Jackson Serialiser).

**Comment by savanpatel** [comment]
But when I call this:
Locker lock = baseOperations.lock(ThrottlerUtil.getLockKey(key));
It returns Locker object (Wrapper over RLcok) containing RLock object for key after locking.
So doesn't redisson takes care of these race conditions?

**Comment by Gladmir** [comment]
So you are calling tryLock after you get the RLock impl. object and you are sure you acquired the lock (within baseOperations.lock (...) call ) ?

Could you share baseOperations.lock call's code?

**Comment by savanpatel** [comment]
/*
     *  Locks on the given key. 
     */
    @Override
    public Locker lock(String key)
    {
       RLock lock = redisson.getLock(key);
       lock.lock(leaseTimeMs, TimeUnit.MILLISECONDS);
       return new Locker(lock);
    }
    

And redisson is 
  private Redisson redisson;

**Comment by Gladmir** [comment]
Please check the threadId like I mentioned earlier, your lock (String key) method seems clear.

**Comment by savanpatel** [comment]
I monitored on redisson and every time on new lock request, it over writes the lock value.

"SET" "amplelock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"2596c222-404c-4827-a33c-728eb8c35378\",\"threadId\":321}" "px" "5000" "nx"
1433853958.412589 [0 176.9.155.232:37491] "SET" "amplelock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"c0741619-0037-4453-adb8-4b1757895bae\",\"threadId\":451}" "px" "5000" "nx"
1433853958.412837 [0 144.76.139.52:35420] "SET" "amplelock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"2596c222-404c-4827-a33c-728eb8c35378\",\"threadId\":337}" "px" "5000" "nx"
1433853958.412906 [0 176.9.155.232:37503] "SET" "amplelock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"c0741619-0037-4453-adb8-4b1757895bae\",\"threadId\":787}" "px" "5000" "nx"
1433853958.412960 [0 144.76.139.52:35435] "SET" "amplelock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"2596c222-404c-4827-a33c-728eb8c35378\",\"threadId\":370}" "px" "5000" "nx"
1433853958.413274 [0 176.9.155.232:37486] "SET" "amplelock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"c0741619-0037-4453-adb8-4b1757895bae\",\"threadId\":782}" "px" "5000" "nx"
1433853958.413369 [0 176.9.155.232:37488] "SET" "amplelock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"c0741619-0037-4453-adb8-4b1757895bae\",\"threadId\":813}" "px" "5000" "nx"
1433853958.413440 [0 176.9.155.232:37528] "SET" "amplelock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"c0741619-0037-4453-adb8-4b1757895bae\",\"threadId\":797}" "px" "5000" "nx"

Have a look at screen shot
![screenshot from 2015-06-09 18 14 15](https://cloud.githubusercontent.com/assets/4772502/8057986/9b2726c6-0ed3-11e5-9d85-2ba778cdabd8.png)

**Comment by Gladmir** [comment]
Whats your redisson version? I want check the source code of it.

**Comment by savanpatel** [comment]
redisson-1.2.1

**Comment by Gladmir** [comment]
Tried with 100 threads, 5 ms waits between lock/unlock calls per thread and couldn't generated your case.

First of all, please upgrade your redisson version to latest 1.2.1 and check your redis monitor log for the SETNX command instead of SET command. Also make sure to use at least Redis 3.0.1, just be sure.

Your monitor output should be like;

1434091509.343215 [0 127.0.0.1:50802] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":97}"
1434091509.343416 [0 127.0.0.1:50829] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":61}"
1434091509.343721 [0 127.0.0.1:50767] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":50}"
1434091509.344046 [0 127.0.0.1:50765] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":58}"
1434091509.344412 [0 127.0.0.1:50764] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":49}"
1434091509.345077 [0 127.0.0.1:50851] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":55}"
1434091509.345137 [0 127.0.0.1:50814] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":102}"
1434091509.345192 [0 127.0.0.1:50827] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":45}"
1434091509.345244 [0 127.0.0.1:50810] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":84}"
1434091509.345297 [0 127.0.0.1:50849] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":94}"
1434091509.345349 [0 127.0.0.1:50812] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":87}"
1434091509.345404 [0 127.0.0.1:50854] "SETNX" "someLock" "{\"@class\":\"org.redisson.RedissonLock$LockValue\",\"counter\":1,\"id\":\"f6a8c65b-8d3d-4042-9dd3-c0e5a2afa70b\",\"threadId\":106}"

Since the command SETNX only updates/sets if the key is missing and Redis's embedded atomicity support, running the same test with multiple independent redisson instances and/or JVMs should not change or break the Lock contract.

**Comment by Gladmir** [comment]
Very simply race generator

```
Config config = new Config();
        config.useSingleServer().setAddress("127.0.0.1:6379");

        final Redisson redisson = Redisson.create(config);

        executorService = Executors.newFixedThreadPool(threadCount);

        final CountDownLatch latch = new CountDownLatch(1);

        for (int i=0 ; i < threadCount; i++) {
            executorService.submit(new Runnable() {
                public void run() {

                    // Wait for the race start
                    try {
                        latch.await();
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    RLock someLock = redisson.getLock("someLock");

                    System.out.println(Thread.currentThread().getName() + ": Trying to acquire lock");

                    someLock.lock();

                    System.out.println(Thread.currentThread().getName() + ": Acquired lock!");


                    try {
                        Thread.sleep(5);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }

                    someLock.unlock();

                }
            });
        }

        // all threads ready to be continue, signal them
        latch.countDown();

        executorService.shutdown();
        try {
            executorService.awaitTermination(1, TimeUnit.MINUTES);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
```

**Comment by savanpatel** [comment]
Updated to latest Redisson version and the problem is solved now. Thanks a lot for your support. :)

**Comment by mrniko** [comment]
@savanpatel  nice!
@Gladmir thanks for you help with support!

**Comment by Gladmir** [comment]
@savanpatel @mrniko :)

**Comment by srijanmehrotra** [comment]
@savanpatel Since your service is running on multiple nodes. Would suggest you to use **lock.isHeldByCurrentThread()** method before unlocking. A sample method would like
`RLock lock = redissonClient().getLock(lockLabel);
try {
  if (lock.tryLock(lockAcquireWaitTime, lockLeaseTime, TimeUnit.MINUTES)) {
   //Action to be performed when lock is acquired.
    lock.unlock();
  }
  Thread.sleep(syncMonitorInterval);
} catch (Exception e) {
  LOG.error("Error..", e);
} finally {
  if (lock != null && lock.isLocked() && lock.isHeldByCurrentThread()) {
    lock.unlock();
    LOG.debug("lock released");
  }
}`
