### ISSUE TITLE
Use Redis client to add a set , but in Redisson got a error

### ISSUE THREAD

**Issue by harborgang** [mrniko/redisson#172]
Redis 3.0.1
Redisson 1.2.0

I got a problem.

Firstly , in redis client , I put a set named "hello", the set numbers are "hello1"  and "hello2"
Second,in Redisson , I get this set .

		RSet  hello = redisson.getSet("hello");
		Iterator it = hello.iterator();
		System.out.println(it.next());
		System.out.println(it.next());

WARN 11:36:59 warn(Slf4JLogger.java:151) - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'hello2': was expecting ('true', 'false' or 'null')
 at [Source: [B@9df354; line: 1, column: 32]
	at org.redisson.codec.JsonJacksonCodec.decodeMapValue(JsonJacksonCodec.java:146)
	at org.redisson.codec.RedisCodecWrapper.decodeMapValue(RedisCodecWrapper.java:67)
	at com.lambdaworks.redis.output.ValueSetScanOutput.set(ValueSetScanOutput.java:19)
	at com.lambdaworks.redis.protocol.RedisStateMachine.decode(RedisStateMachine.java:112)
	at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:71)
	at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:52)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:619)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'hello2': was expecting ('true', 'false' or 'null')
 at [Source: [B@9df354; line: 1, column: 32]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1419)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:508)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3201)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2360)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:794)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:690)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3090)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3036)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2225)
	at org.redisson.codec.JsonJacksonCodec.decodeMapValue(JsonJacksonCodec.java:144)
	... 19 more

**Comment by biniama** [comment]
what was the solution?

**Comment by jackygurui** [comment]
The incorrect encoding was used.

**Comment by biniama** [comment]
thanks for the fast reply. Can you be more specific and share the solution code?

**Comment by jackygurui** [comment]
I suggest you open a new issue ticket following the template since the version you are using is likely different from the PO's
