### ISSUE TITLE
Unix Sockets 

### ISSUE THREAD

**Issue by ahmedaswai** [mrniko/redisson#173]
Do you have a plan to develop  the client to be able to use  unix sockets instead of tcp.

**Comment by mrniko** [comment]
but unix sockets useful only then using loopback interface, isn't it?

**Comment by hepin1989** [comment]
he means that the redis and the redisson on the same server right?

**Comment by mrniko** [comment]
in netty unix sockets implemented via epoll transport https://github.com/netty/netty/pull/3344
So i need to add epoll transport support.

**Comment by mrniko** [comment]
Done!

**Comment by ahmedaswai** [comment]
Thank you I will test it and I will give my results

**Comment by ahmedaswai** [comment]
Sorry I tried to test it on my linux server and I am getting the next exception , could you help to fix this issue 

03:45:01.882 [main] DEBUG i.n.u.internal.NativeLibraryLoader - -Dio.netty.netty.workdir: /tmp (io.netty.tmpdir)
Java HotSpot(TM) Server VM warning: You have loaded library /tmp/libnetty-transport-native-epoll4497405352061061375.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libnetty-transport-native-epoll4497405352061061375.so: /tmp/libnetty-transport-native-epoll4497405352061061375.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:50)
	at io.netty.channel.epoll.EpollEventArray.<clinit>(EpollEventArray.java:40)
	at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:65)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:76)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:61)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:49)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:41)
	at org.redisson.connection.MasterSlaveConnectionManager.init(MasterSlaveConnectionManager.java:135)
	at org.redisson.connection.MasterSlaveConnectionManager.init(MasterSlaveConnectionManager.java:107)
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:38)
	at org.redisson.Redisson.<init>(Redisson.java:71)
	at org.redisson.Redisson.create(Redisson.java:103)

**Comment by mrniko** [comment]
which transport-epoll lib you have plugged in thisone `io.netty:netty-transport-native-epoll:4.0.29.Final:linux-x86_64`?

**Comment by ahmedaswai** [comment]
I am using netty 4.0.30 all final

**Comment by mrniko** [comment]
take a look at similar issue: https://github.com/mrniko/redisson/issues/184, @pluttrell wrote: `io.netty:netty-transport-native-epoll:4.0.29.Final` not helped, but `io.netty:netty-transport-native-epoll:4.0.29.Final:linux-x86_64` does. Have you tried netty-transport-native-epoll lib with `linux-x86_64` suffix?
