### ISSUE TITLE
NPE when call queue.poll

### ISSUE THREAD

**Issue by hepin1989** [mrniko/redisson#181]
```scala
      val bytes = queue.poll(10, TimeUnit.SECONDS)
```
java.lang.NullPointerException
	at org.redisson.RedissonBlockingQueue$2.execute(RedissonBlockingQueue.java:74)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:296)
	at org.redisson.connection.MasterSlaveConnectionManager.write(MasterSlaveConnectionManager.java:285)
	at org.redisson.RedissonBlockingQueue.poll(RedissonBlockingQueue.java:71)
	at service.StatisticWorker$$anonfun$receive$1.applyOrElse(StatisticService.scala:143)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
	at service.StatisticWorker.aroundReceive(StatisticService.scala:103)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by mrniko** [comment]
Can't reproduce. Here is a testcase i have used:

```
        RBlockingQueue<Integer> queue1 = redisson.getBlockingQueue("queue1");
        queue1.put(1);

        queue1.poll(10, TimeUnit.SECONDS);
```

**Comment by mattcg** [comment]
@mrniko I can replicate this consistently. Try running the following.

```java
RBlockingQueue<Integer> queue1 = redisson.getBlockingQueue("queue1");
queue1.put(1);
queue1.poll(10, TimeUnit.SECONDS);
queue1.poll(10, TimeUnit.SECONDS);
```

The second call to `poll` will wait ten seconds, then you'll get a `NullPointerException`.

The issue is that `io.netty.util.concurrent.Future#getNow` returns `null` if the future is not done yet, which in this case happens when the queue is drained. That method is called by `com.lambdaworks.redis.RedisAsyncConnection#awaitInterruptibly`, which in turn is called by `blpop`, which is called in `poll`.

**Comment by mrniko** [comment]
fixed

**Comment by mattcg** [comment]
Thank you! :sparkles: :sparkles: :sparkles:

**Comment by hepin1989** [comment]
thanks too:P

**Comment by hepin1989** [comment]
and sorry I didn't come up with a producer.:( super busy.thanks again.
