### ISSUE TITLE
Are the recent Netty related features alerting Netty for other libraries?

### ISSUE THREAD

**Issue by pluttrell** [mrniko/redisson#184]
Today attempted to migrate Redisson from version 1.2.1 to 1.3.0 and that caused the 2.1.6 version of the DataStax Java driver to write a WARN + stack trace instead of an INFO to the log.

With `org.redisson:redisson:1.2.1`, I see:

```
INFO  [com.datastax.driver.core.NettyUtil] (MSC service thread 1-2) Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
```

With `org.redisson:redisson:1.3.0`, I see:

```
WARN  [com.datastax.driver.core.NettyUtil] (MSC service thread 1-1) Found Netty's native epoll transport in the classpath, but epoll is not available. Using NIO instead.: java.lang.UnsatisfiedLinkError: no netty-transport-native-epoll in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857) [rt.jar:1.8.0_25]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) [rt.jar:1.8.0_25]
	at java.lang.System.loadLibrary(System.java:1119) [rt.jar:1.8.0_25]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:168) [netty-common-4.0.29.Final.jar:4.0.29.Final]
	at io.netty.channel.epoll.Native.<clinit>(Native.java:50) [netty-transport-native-epoll-4.0.29.Final.jar:4.0.29.Final]
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:30) [netty-transport-native-epoll-4.0.29.Final.jar:4.0.29.Final]
	at java.lang.Class.forName0(Native Method) [rt.jar:1.8.0_25]
	at java.lang.Class.forName(Class.java:260) [rt.jar:1.8.0_25]
	at com.datastax.driver.core.NettyUtil.<clinit>(NettyUtil.java:68) [cassandra-driver-core-2.2.0-rc1.jar:]
	at com.datastax.driver.core.NettyOptions.eventLoopGroup(NettyOptions.java:101) [cassandra-driver-core-2.2.0-rc1.jar:]
	at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:698) [cassandra-driver-core-2.2.0-rc1.jar:]
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1244) [cassandra-driver-core-2.2.0-rc1.jar:]
	at com.datastax.driver.core.Cluster.init(Cluster.java:159) [cassandra-driver-core-2.2.0-rc1.jar:]
	at com.datastax.driver.core.Cluster.connect(Cluster.java:249) [cassandra-driver-core-2.2.0-rc1.jar:]
	at com.datastax.driver.core.Cluster.connect(Cluster.java:282) [cassandra-driver-core-2.2.0-rc1.jar:]
	...
```	

I also tried version 2.2.0-rc1 of the DataStax Java driver and see the same thing.

I also tried adding a dependency on `io.netty:netty-transport-native-epoll:4.0.29.Final`, which I believe contains the linux-x86_64 jars but still see the same thing.

For reference, I'm deploying to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-44-generic x86_64).

Please advise.

Thanks,
Peter Luttrell

**Comment by tolbertam** [comment]
I posted a [reply](https://groups.google.com/a/lists.datastax.com/forum/#!topic/java-driver-user/QgwtAB7Mhn8) to @pluttrell's question on the java-driver user group.  I think redisson should make netty-transport-native-epoll an optional dependency since an architecture-specific version is required anyways to properly use epoll.  In addition, this would prevent pulling down the jar into a user's project unless they needed it, at which point they would add the architecture-specific classifier dependency anyways (which is already a requirement to use epoll).

**Comment by pluttrell** [comment]
Adding a dependency on 'io.netty:netty-transport-native-epoll:4.0.29.Final:linux-x86_64' does work to resolve the WARN issue. And I agree with @tolbertam that Redisson should make this dependency optional, just as DataStax does, as that's the core issue.
