### ISSUE TITLE
can't stop via shutdown

### ISSUE THREAD

**Issue by hepin1989** [mrniko/redisson#185]
when call shutdown(),it cause these error again and again and never stop the application.
I single the JVM via Ctrl + D and there is a shutdown() hooked in Play's lifecycle's onShutdown() callback.
```scala
  lazy val get: Redisson = {
    val redissonConfig = parseRedissonConfig(config)
    val redisson = Redisson.create(redissonConfig)
    lifecycle.addStopHook(() => Future.successful {
      redisson.shutdown()
    })
    redisson
  }
```
```
[warn] - io.netty.channel.AbstractChannel - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x76514d59]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:672) ~[io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:264) ~[io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:655) ~[io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:458) ~[io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:68) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:56) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:75) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:324) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:157) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:113) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:176) [org.redisson.redisson-1.3.0.jar:na]
	at com.lambdaworks.redis.RedisClient.connectAsync(RedisClient.java:149) [org.redisson.redisson-1.3.0.jar:na]
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:132) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:127) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:770) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:249) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:217) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.RedissonList.addAllAsync(RedissonList.java:156) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.RedissonList.addAll(RedissonList.java:148) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.RedissonList.add(RedissonList.java:96) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.RedissonQueue.offer(RedissonQueue.java:43) [org.redisson.redisson-1.3.0.jar:na]
	at service.Pumper$$anonfun$receive$1.applyOrElse(StatisticService.scala:59) [cn.q-game.statisticserver-1.0-SNAPSHOT-sans-externalized.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:475) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at service.Pumper.aroundReceive(StatisticService.scala:53) [cn.q-game.statisticserver-1.0-SNAPSHOT-sans-externalized.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:256) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:223) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:233) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]

```

**Comment by mrniko** [comment]
> it cause these error again and again and never stop the application

Only one type of error you have provided above?

**Comment by hepin1989** [comment]
maybe plus these?
this time it complete stop.
I think it worth to add  method 
```shutdownGracefully```and change ```shutdown``` to ```shutdownNow```. 
```
[ERROR] [07/10/2015 19:12:23.708] [application-akka.actor.default-dispatcher-4] [akka://application/user/$a] Connection is closed
com.lambdaworks.redis.RedisConnectionClosedException: Connection is closed
	at com.lambdaworks.redis.RedisAsyncConnection.dispatch(RedisAsyncConnection.java:1246)
	at com.lambdaworks.redis.RedisAsyncConnection.rpush(RedisAsyncConnection.java:657)
	at org.redisson.RedissonList$5.execute(RedissonList.java:159)
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:252)
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:217)
	at org.redisson.RedissonList.addAllAsync(RedissonList.java:156)
	at org.redisson.RedissonList.addAll(RedissonList.java:148)
	at org.redisson.RedissonList.add(RedissonList.java:96)
	at org.redisson.RedissonQueue.offer(RedissonQueue.java:43)
	at service.Pumper$$anonfun$receive$1.applyOrElse(StatisticService.scala:72)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:475)
	at service.Pumper.aroundReceive(StatisticService.scala:66)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:256)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:233)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
and :
```
[warn] - io.netty.channel.AbstractChannel - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x770bd872]
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:672) ~[io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:264) ~[io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:655) ~[io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:458) ~[io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:68) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:56) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:75) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:324) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:157) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:113) [io.netty.netty-all-4.1.0.Beta5.jar:4.1.0.Beta5]
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:176) [org.redisson.redisson-1.3.0.jar:na]
	at com.lambdaworks.redis.RedisClient.connectAsync(RedisClient.java:149) [org.redisson.redisson-1.3.0.jar:na]
	at com.lambdaworks.redis.RedisClient.connect(RedisClient.java:132) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:127) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:770) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:249) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:217) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.RedissonList.addAllAsync(RedissonList.java:156) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.RedissonList.addAll(RedissonList.java:148) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.RedissonList.add(RedissonList.java:96) [org.redisson.redisson-1.3.0.jar:na]
	at org.redisson.RedissonQueue.offer(RedissonQueue.java:43) [org.redisson.redisson-1.3.0.jar:na]
	at service.Pumper$$anonfun$receive$1.applyOrElse(StatisticService.scala:72) [cn.q-game.statisticserver-1.0-SNAPSHOT-sans-externalized.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:475) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at service.Pumper.aroundReceive(StatisticService.scala:66) [cn.q-game.statisticserver-1.0-SNAPSHOT-sans-externalized.jar:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:256) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:223) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:233) [com.typesafe.akka.akka-actor_2.11-2.4-M2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]
```
and：
```
[ERROR] [07/10/2015 19:12:25.705] [application-akka.actor.default-dispatcher-2] [akka://application/user/$a] cannot be started once stopped
java.lang.IllegalStateException: cannot be started once stopped
	at io.netty.util.HashedWheelTimer.start(HashedWheelTimer.java:269)
	at io.netty.util.HashedWheelTimer.newTimeout(HashedWheelTimer.java:332)
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:259)
	at org.redisson.connection.MasterSlaveConnectionManager.writeAsync(MasterSlaveConnectionManager.java:217)
	at org.redisson.RedissonList.addAllAsync(RedissonList.java:156)
	at org.redisson.RedissonList.addAll(RedissonList.java:148)
	at org.redisson.RedissonList.add(RedissonList.java:96)
	at org.redisson.RedissonQueue.offer(RedissonQueue.java:43)
	at service.Pumper$$anonfun$receive$1.applyOrElse(StatisticService.scala:72)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:475)
	at service.Pumper.aroundReceive(StatisticService.scala:66)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:256)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:233)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
but finally it stopped this time

**Comment by mrniko** [comment]
please check

**Comment by mrniko** [comment]
@hepin1989 is it works now?

**Comment by hepin1989** [comment]
@mrniko I will upgrade it then and test it.I am not at workspace :P.
thanks,will keep you update later.

**Comment by mrniko** [comment]
@hepin1989 i'll wait for your reply before integration into 2.0 branch

**Comment by hepin1989** [comment]
I have tried the 1.3.1-snapshort via clone it and mvn install,now the application don't respect the 
```Ctrl + C/D``` ,and continue running.seems like trapped somewhere.

**Comment by mrniko** [comment]
could provide a testcase? how to reproduce it?

**Comment by mrniko** [comment]
@hepin1989 please check it again

**Comment by hepin1989** [comment]
@mrniko OK,waiting a moment.

**Comment by hepin1989** [comment]
@mrniko it works now,but I think you would better add some warnning message for that :
after the shutdown is called,dropping the future job,and logging the dropping with warning.WDYT?
thanks, for the great lib,sorry for I don't come up with some contribution.:(

**Comment by hepin1989** [comment]
BTW,seems the snapshot version haven't published to maven center,I have to install it locally,could you please check?

**Comment by mrniko** [comment]
1.3.1 will be published in central repo in few days
