### ISSUE TITLE
Cluster mode "Too many open files" (java.net.SocketException)

### ISSUE THREAD

**Issue by mgreenstein** [mrniko/redisson#222]
Cluster mode Redisson client running out of files (sockets) in communicating with Redis.

This occurs even when the Redisson client is not receiving any requests.  It must be a problem with cluster mode connectivity.

To reproduce, I simply made two calls to my server using Redisson to set a simple value on Redis and then retrieve a simple value.  Then we did nothing at all.

It appears the Redisson in cluster mode is continually opening new socket connections but not closing existing ones.

After about an hour, we started seeing the following exceptions in our server logs.

Note:  I am may have seen a similar behavior in sentinel mode.  We recently upgraded Redisson to 2.1.0 from 1.1.5.  Could this be a more general problem?  We will upgrade to 2.1.1 and test again.

Thank you very much.

--Michael

====================================

test machine

Aug 14, 2015 8:49:18 AM org.apache.tomcat.util.net.JIoEndpoint$Acceptor run
SEVERE: Socket accept failed
java.net.SocketException: Too many open files
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at org.apache.tomcat.util.net.DefaultServerSocketFactory.acceptSocket(DefaultServerSocketFactory.java:60)
        at org.apache.tomcat.util.net.JIoEndpoint$Acceptor.run(JIoEndpoint.java:220)
        at java.lang.Thread.run(Thread.java:745)

Aug 14, 2015 8:49:18 AM org.apache.tomcat.util.net.JIoEndpoint$Acceptor run
SEVERE: Socket accept failed
java.net.SocketException: Too many open files
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at org.apache.tomcat.util.net.DefaultServerSocketFactory.acceptSocket(DefaultServerSocketFactory.java:60)
        at org.apache.tomcat.util.net.JIoEndpoint$Acceptor.run(JIoEndpoint.java:220)
        at java.lang.Thread.run(Thread.java:745)

Aug 14, 2015 8:49:18 AM org.apache.tomcat.util.net.JIoEndpoint$Acceptor run

======================================

Connections on the Redis server continually increase:

[root@qa-mq01.artfact.local ~ $ date; netstat -an | grep 192.168.10.135 | wc -l
Tue Aug 18 09:55:51 EDT 2015
2523

[root@qa-mq01.artfact.local ~ $ date; netstat -an | grep 192.168.10.135 | wc -l
Tue Aug 18 09:56:04 EDT 2015
2536

[root@qa-mq01.artfact.local ~ $ date; netstat -an | grep 192.168.10.135 | wc -l
Tue Aug 18 10:12:13 EDT 2015
3490

====================================

Another instance just now from the test machine

Aug 18, 2015 10:29:36 AM org.apache.tomcat.util.net.JIoEndpoint$Acceptor run
SEVERE: Socket accept failed
java.net.SocketException: Too many open files
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at org.apache.tomcat.util.net.DefaultServerSocketFactory.acceptSocket(DefaultServerSocketFactory.java:60)
        at org.apache.tomcat.util.net.JIoEndpoint$Acceptor.run(JIoEndpoint.java:220)
        at java.lang.Thread.run(Thread.java:745)

Aug 18, 2015 10:29:36 AM org.apache.tomcat.util.net.JIoEndpoint$Acceptor run
SEVERE: Socket accept failed
java.net.SocketException: Too many open files
        at java.net.PlainSocketImpl.socketAccept(Native Method)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at org.apache.tomcat.util.net.DefaultServerSocketFactory.acceptSocket(DefaultServerSocketFactory.java:60)
        at org.apache.tomcat.util.net.JIoEndpoint$Acceptor.run(JIoEndpoint.java:220)
        at java.lang.Thread.run(Thread.java:745)

Aug 18, 2015 10:29:36 AM org.apache.tomcat.util.net.JIoEndpoint$Acceptor run
SEVERE: Socket accept failed
java.net.SocketException: Too many open files

**Comment by mrniko** [comment]
fixed. Please check

**Comment by mgreenstein** [comment]
I just tested this fix.  It seems to be working.  Thank you very much!

**Comment by mrniko** [comment]
You're welcome!

**Comment by mgreenstein** [comment]
Nikita,


Thank you very much for the quick response and fix.  It seems to be working better now.


We are testing cases when the Redis cluster changes (nodes are added, removed, have problems, etc.)  I think I mentioned this before and you responded to use the CLUSTER_NODES command.  I wasn't able to figure out how to use it through Redisson.


My co-worker, Julie, said to say, "Spacibo."


--Michael


________________________________

**Comment by mrniko** [comment]
You don't need to use CLUSTER_NODES command Redisson will do it for you :)

**Comment by mgreenstein** [comment]
I believe this is correct.  I am going to forward a picture in a separate email.


Thank you very much.


________________________________
