### ISSUE TITLE
reconnection functionality doesn't work with AUTH enabled on redis

### ISSUE THREAD

**Issue by turbospaces** [mrniko/redisson#242]
If I enable security on redis, re-connection functionality no longer works - wihout security redisson works as expected and re-connects.

Steps to reproduce: enable redis security, run code below and restart redis somewhere in the middle.

```java
        Config config = new Config();
        config.useSingleServer().setAddress( "127.0.0.1:6379" ).setPassword( "foobared" );
        Redisson redisson = Redisson.create( config );
        redisson.flushdb();

        for ( int i = 0; i < 100; i++ ) {
            RAtomicLong rAtomicLong = redisson.getAtomicLong( "x" );
            System.out.println( rAtomicLong.addAndGet( 1 ) );
            Thread.sleep( 1 * 1000 );
        }

        redisson.shutdown();
```

Exception
```java
Exception in thread "main" org.redisson.client.RedisException: NOAUTH Authentication required.. channel: [id: 0x1e26a078, /127.0.0.1:57780 => /127.0.0.1:6379]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:168)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mrniko** [comment]
already fixed in current master branch

**Comment by Gyuyeol** [comment]
I have same issue on version 3.7.5

1. Start redis docker container
2. Run the code below
3. Stop redis docker container
  !! Exception !!
4. Start redis docker container
  !! Exception !! continues

```
org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=31, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://localhost:6379], nodeType=MASTER, firstFail=0]]], connection: [id: 0x8fbae8b9, L:0.0.0.0/0.0.0.0:62477], command: (GET), params: [test]
```

```
Config config = new Config();
        SingleServerConfig serverConfig = config.useSingleServer()
        .setAddress("redis://localhost:6379")
        .setTimeout(600)
        .setConnectTimeout(1000)
        .setConnectionMinimumIdleSize(32)
        .setDnsMonitoringInterval(1000)
        .setRetryInterval(150)
        .setRetryAttempts(1);
        
        serverConfig.setPassword("redis-cli");

        RedissonClient redissonClient = Redisson.create(config);

        for (int i = 0; i < 100; i++) {
            try {

                Thread.sleep(5000);

                RBucket<String> target = redissonClient.getBucket("test", StringCodec.INSTANCE);
                System.out.println(target.get());
            } catch (Exception e) {
                if (redissonClient.isShutdown()) {
                    System.out.println("isShutdown: true");
                }

                if (redissonClient.isShuttingDown()) {
                    System.out.println("isShuttingDown: true");
                }

                System.err.println(e.toString());
            }
        }

        redissonClient.shutdown();
```

**Comment by mrniko** [comment]
@Gyuyeol 

I don't see `NOAUTH Authentication` error in your log

**Comment by Gyuyeol** [comment]
@mrniko 

I changed ConnectionMinimumIdleSize to 1 for short log

here is full log

> 
> [redisson-netty-1-8] INFO org.redisson.connection.pool.MasterConnectionPool - 1 connections initialized for localhost/127.0.0.1:6379
> 
> [redisson-netty-1-7] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for localhost/127.0.0.1:6379
> 
> dataFromRedis
> 
> dataFromRedis
> 
> [redisson-netty-1-21] WARN org.redisson.client.handler.ConnectionWatchdog - Can't connect RedisPubSubConnection@1612953060 [redisClient=[addr=redis://localhost:6379], channel=[id: 0xe6d9260b, L:0.0.0.0/0.0.0.0:2948]] to localhost/127.0.0.1:6379
> 
> [redisson-netty-1-22] WARN org.redisson.client.handler.ConnectionWatchdog - Can't connect RedisConnection@1480159984 [redisClient=[addr=redis://localhost:6379], channel=[id: 0x4b2b001f, L:0.0.0.0/0.0.0.0:2947]] to localhost/127.0.0.1:6379
> 
> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), command params: [redis-cli], Redis client: [addr=redis://localhost:6379]
> 
> 	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212)
> 
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
> 
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
> 
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> 
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 
> 	at java.lang.Thread.run(Thread.java:748)
> 
> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), command params: [redis-cli], Redis client: [addr=redis://localhost:6379]
> 
> 	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212)
> 
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
> 
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
> 
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> 
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 
> 	at java.lang.Thread.run(Thread.java:748)
> 
> [redisson-netty-1-2] WARN org.redisson.client.handler.ConnectionWatchdog - Can't connect RedisPubSubConnection@872967200 [redisClient=[addr=redis://localhost:6379], channel=[id: 0xdb347650, L:/127.0.0.1:2968 ! R:localhost/127.0.0.1:6379]] to localhost/127.0.0.1:6379
> 
> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), command params: [redis-cli], Redis client: [addr=redis://localhost:6379]
> 
> 	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212)
> 
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
> 
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
> 
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> 
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 
> 	at java.lang.Thread.run(Thread.java:748)
> 
> [redisson-netty-1-3] WARN org.redisson.client.handler.ConnectionWatchdog - Can't connect RedisConnection@80527169 [redisClient=[addr=redis://localhost:6379], channel=[id: 0x13458d31, L:/127.0.0.1:2967 ! R:localhost/127.0.0.1:6379]] to localhost/127.0.0.1:6379
> 
> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), command params: [redis-cli], Redis client: [addr=redis://localhost:6379]
> 
> 	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212)
> 
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
> 
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
> 
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> 
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 
> 	at java.lang.Thread.run(Thread.java:748)
> 
> org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=0, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://localhost:6379], nodeType=MASTER, firstFail=0]]], connection: [id: 0x4b2b001f, L:0.0.0.0/0.0.0.0:2947], command: (GET), params: [test]
> 
> [redisson-netty-1-6] WARN org.redisson.client.handler.ConnectionWatchdog - Can't connect RedisPubSubConnection@137529361 [redisClient=[addr=redis://localhost:6379], channel=[id: 0x9ff0c60c, L:/127.0.0.1:2969 ! R:localhost/127.0.0.1:6379]] to localhost/127.0.0.1:6379
> 
> org.redisson.client.RedisTimeoutException: Command execution timeout for command: (AUTH), command params: [redis-cli], Redis client: [addr=redis://localhost:6379]
> 
> 	at org.redisson.client.RedisConnection$2.run(RedisConnection.java:212)
> 
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
> 
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
> 
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
> 
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
> 
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 
> 	at java.lang.Thread.run(Thread.java:748)
> 
> org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=0, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://localhost:6379], nodeType=MASTER, firstFail=0]]], connection: [id: 0x4b2b001f, L:0.0.0.0/0.0.0.0:2947], command: (GET), params: [test]
> 
> org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=0, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://localhost:6379], nodeType=MASTER, firstFail=0]]], connection: [id: 0x4b2b001f, L:0.0.0.0/0.0.0.0:2947], command: (GET), params: [test]
> 
> org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=0, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://localhost:6379], nodeType=MASTER, firstFail=0]]], connection: [id: 0x4b2b001f, L:0.0.0.0/0.0.0.0:2947], command: (GET), params: [test]
> 
> org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=0, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://localhost:6379], nodeType=MASTER, firstFail=0]]], connection: [id: 0x4b2b001f, L:0.0.0.0/0.0.0.0:2947], command: (GET), params: [test]
> 
> org.redisson.client.WriteRedisConnectionException: Unable to send command! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=0, freeConnectionsCounter=63, freezed=false, freezeReason=null, client=[addr=redis://localhost:6379], nodeType=MASTER, firstFail=0]]], connection: [id: 0x4b2b001f, L:0.0.0.0/0.0.0.0:2947], command: (GET), params: [test]
>

**Comment by emmanuj** [comment]
Still seeing this while try to deploy on heroku:

```
2018-12-22T04:26:10.753603+00:00 app[web.1]: 2018-12-22 04:26:10.732 ERROR --- [isson-netty-1-4] o.r.client.handler.CommandPubSubDecoder  : Error: NOAUTH Authentication required. channel: [id: 0x11c347b0, L:/172.16.125.54:41646 - R:ec2-35-175-44-82.compute-1.amazonaws.com/35.175.44.82:42859] data: null
2018-12-22T04:26:12.340326+00:00 app[web.1]: 2018-12-22 04:26:12.338 ERROR --- [ost-startStop-1] o.s.boot.SpringApplication               : Application startup failed
2018-12-22T04:26:12.340341+00:00 app[web.1]:
2018-12-22T04:26:12.340343+00:00 app[web.1]: java.util.concurrent.CompletionException: org.redisson.client.RedisTimeoutException
2018-12-22T04:26:12.340344+00:00 app[web.1]: at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:197)
2018-12-22T04:26:12.340345+00:00 app[web.1]: at org.redisson.misc.RedissonPromise.await(RedissonPromise.java:206)
2018-12-22T04:26:12.340347+00:00 app[web.1]: at org.redisson.command.CommandAsyncService.syncSubscription(CommandAsyncService.java:159)
2018-12-22T04:26:12.340348+00:00 app[web.1]: at org.redisson.RedissonTopic.addListener(RedissonTopic.java:126)
2018-12-22T04:26:12.340349+00:00 app[web.1]: at org.redisson.RedissonTopic.addListener(RedissonTopic.java:103)
2018-12-22T04:26:12.340350+00:00 app[web.1]: at org.redisson.QueueTransferTask.start(QueueTransferTask.java:86)
2018-12-22T04:26:12.340351+00:00 app[web.1]: at org.redisson.QueueTransferService.schedule(QueueTransferService.java:34)
2018-12-22T04:26:12.340353+00:00 app[web.1]: at org.redisson.RedissonExecutorService.registerWorkers(RedissonExecutorService.java:299)
2018-12-22T04:26:12.340354+00:00 app[web.1]: at org.redisson.RedissonExecutorService.registerWorkers(RedissonExecutorService.java:241)
2018-12-22T04:26:12.340355+00:00 app[web.1]: at org.redisson.api.RExecutorService$registerWorkers.call(Unknown Source)
2018-12-22T04:26:12.340356+00:00 app[web.1]: at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
2018-12-22T04:26:12.340358+00:00 app[web.1]: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
2018-12-22T04:26:12.340359+00:00 app[web.1]: at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
2018-12-22T04:26:12.340360+00:00 app[web.1]: at app.core.RedissonService.$tt__init(RedissonService.groovy:42)
```
