### ISSUE TITLE
NPE in pub/sub

### ISSUE THREAD

**Issue by feci** [mrniko/redisson#259]
[WARNING 14.10.2015 12:14:58.968] io.netty.channel.DefaultChannelPipeline-An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:425)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.redisson.client.handler.CommandDecoder.messageDecoder(CommandDecoder.java:267)
        at org.redisson.client.handler.CommandDecoder.decodeMulti(CommandDecoder.java:202)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:189)
        at org.redisson.client.handler.CommandDecoder.decodeMulti(CommandDecoder.java:208)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:189)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:97)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)
        ... 18 more

**Comment by mrniko** [comment]
Which version did you use?

**Comment by mrniko** [comment]
Fixed in  #253
