### ISSUE TITLE
RMap.putAll not working.

### ISSUE THREAD

**Issue by Master-chan** [mrniko/redisson#265]
I have RMap<String, String> and static map with default values which I need to save but RMap.putAll keeps throwing exception:

```
me.mc2.internal.redisson.client.RedisException: ERR wrong number of arguments for 'hmset' command. channel: [id: 0x64225355, /109.120.149.72:45005 => /109.120.149.72:6379] command: CommandData [promise=DefaultPromise@1cfa79f9(incomplete), command=RedisCommand [name=HMSET, subName=null], params=[player:d2c75e6d-f726-4433-ab71-259e04cca4de:settings, {LANGUAGE=ENGLISH}], codec=me.mc2.internal.redisson.client.codec.StringCodec@3803fe0]
    at me.mc2.internal.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:168)
    at me.mc2.internal.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
    at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by mrniko** [comment]
fixed
