### ISSUE TITLE
RList add at index inserts data in different format causing an exception on read

### ISSUE THREAD

**Issue by randyhoude72** [mrniko/redisson#280]
Hi,

I have code running against redisson 2.1.3 that was adding a value at an index and after the add is called the list can no longer read, throwing this exception:

	org.redisson.client.RedisException: Unexpected exception while processing command
		at org.redisson.CommandExecutorService.get(CommandExecutorService.java:185)
		at org.redisson.RedissonObject.get(RedissonObject.java:48)
		at org.redisson.RedissonList.getValue(RedissonList.java:291)
		at org.redisson.RedissonList.get(RedissonList.java:287)
		at com.senet.cache.redis.redisson.RedissonCache.main(RedissonCache.java:845)
	Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('b' (code 98)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 		at [Source: io.netty.buffer.ByteBufInputStream@7b205dbd; line: 1, column: 2]
		at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
		at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
		at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:453)
		at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2278)
		at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:779)
		at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:665)
		at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:2926)
		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2873)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2080)
		at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:59)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:179)
		at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:104)
		at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
		at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
		at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
		at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
		at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
		at java.lang.Thread.run(Thread.java:745)

I wrote a simple test to see what was going on.  The code from test1 executes without issue.  The code for test2 throws the exception on the first pass through the for loop.

		    RList<String> test1 = redisson.getList("test1");
		    test1.add("foo");
		    test1.add("bar");
		    for (int i=0; i < test1.size(); i++) {
		     	logger.error("Got(" + (i+1)+ "): " + test1.get(i));
		    }
		    
		    RList<String> test2 = redisson.getList("test2");
		    test2.add("foo");
		    test2.add(0, "bar");
		    
		    for (int i=0; i < test2.size(); i++) {
		    	logger.error("Got(" + (i+1)+ "): " + test2.get(i));
		     }

I queried the redis server and here are the two lists.  In test 2 you can see that bar does not get the escaped quotes around it.

     127.0.0.1:6379> lrange test1 0 -1
     1) "\"foo\""
     2) "\"bar\""
     127.0.0.1:6379> lrange test2 0 -1
     1) "bar"
     2) "\"foo\""
     127.0.0.1:6379>

**Comment by mrniko** [comment]
> 1) "bar"

it has a wrong json-format. You should implement your own codec to handle it correctly.

**Comment by randyhoude72** [comment]
Yes, I see that. I am not putting the JSON formatting on any of the other strings either though.  Why is the add with index treating the data differently than the add?

**Comment by mrniko** [comment]
> I am not putting the JSON formatting on any of the other strings either though

No, you did it. "\"foo\"" - this a correct json-string

**Comment by randyhoude72** [comment]
foo is not being set as a JSON string:

       RList<String> test2 = redisson.getList("test2");
        test2.add("foo");
        test2.add(0, "bar");

**Comment by mrniko** [comment]
It encoded to "\"foo\"" by json encoder when Redisson put it in Redis

**Comment by randyhoude72** [comment]
So the add(index, object)  method does not go through the same encoder when Redisson puts it in Redis?

**Comment by mrniko** [comment]
I confirm, it's a bug

**Comment by mrniko** [comment]
fixed

**Comment by randyhoude72** [comment]
Thank you!
