### ISSUE TITLE
RLock did not work

### ISSUE THREAD

**Issue by monoceros** [mrniko/redisson#329]
It's very wired. I just run a very simple test case to try redisson lock. But the result is not good. 
Can anyone show me why RLock didn't work?

```java
//here is my codes
		for (int k = 0; k < 10; k++)
			new Thread() {
				public void run() {
					try {
						Thread.sleep(1000 + new Random().nextInt(100));
					} catch (InterruptedException e) {
					}

					RedissonClient redisson = Redisson.create(config);
					RLock lock = redisson.getLock("anyLock");
					lock.lock();

					RAtomicLong atomicLong = redisson.getAtomicLong("anyAtomicLong");
					long i = atomicLong.get();
					i++;
					atomicLong.set(i);
					System.out.println("number is: " + atomicLong.get());

					lock.unlock();
					redisson.shutdown();
				}
			}.start();
```
The results are as below. It seems the lock failed completely.
number is: 1
number is: 2
number is: 3
number is: 5
number is: 5
number is: 6
number is: 6
number is: 7
number is: 8
number is: 8

**Comment by mrniko** [comment]
It's really wired. Could you please show a Redisson `config` object

**Comment by monoceros** [comment]
Very simple:
		final Config config = new Config();
		config.useSingleServer().setAddress("IP:6379");

**Comment by mrniko** [comment]
Redisson and Redis version? also OS version

**Comment by monoceros** [comment]
My point is that I don't mind to get some exception when I remove "new Random().nextInt(100)". That's another issue. But I cannot accept the number sequence is totally wrong.

**Comment by mrniko** [comment]
I run your test and output is:

number is: 1
number is: 2
number is: 3
number is: 4
number is: 5
number is: 6
number is: 7
number is: 8
number is: 9
number is: 10

**Comment by mrniko** [comment]
So please tell me Redisson version, Redis version and OS version which you used.

**Comment by monoceros** [comment]
Redis 3.0.5
Redisson  2.2.2
OS Ubuntu 14.04

**Comment by monoceros** [comment]
Another try:
SLF4J: The following loggers will not work because they were created
SLF4J: during the default configuration phase of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: The following loggers will not work because they were created
SLF4J: during the default configuration phase of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
SLF4J: org.redisson.connection.SingleConnectionManager
Exception in thread "Thread-1" org.redisson.client.RedisConnectionException: Can't init enough connections amount! from /45.118.132.208:6379
	at org.redisson.misc.ConnectionPool$2.operationComplete(ConnectionPool.java:94)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:592)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
number is: 29
Exception in thread "Thread-3" org.redisson.client.RedisConnectionException: Can't init enough connections amount! from /45.118.132.208:6379
	at org.redisson.misc.ConnectionPool$2.operationComplete(ConnectionPool.java:94)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:592)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-5" org.redisson.client.RedisConnectionException: Can't init enough connections amount! from /45.118.132.208:6379
	at org.redisson.misc.ConnectionPool$2.operationComplete(ConnectionPool.java:94)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:592)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Unknown Source)
number is: 30
number is: 31
number is: 32
number is: 32
number is: 32
number is: 33

**Comment by mrniko** [comment]
`Can't init enough connections amount!` it seems like it can't connect to server at all

**Comment by mrniko** [comment]
@monoceros it's a regression bug since 2.2.2 version

**Comment by mrniko** [comment]
Fixed

**Comment by monoceros** [comment]
Great. It do be fixed in 2.2.3. Thank you all, :-)

BTW. Do you ever think implement a distributed version of Semaphore? I think it's more popular than CountDownLatch. We can use Lock to simulate its function. But a original one is supposed to be more efficient.

**Comment by mrniko** [comment]
@monoceros 2.2.3 version already released. I planned to implement Semaphore in nearest versions. But if you requests it I'll do it in 2.2.4. Here is the task https://github.com/mrniko/redisson/issues/207

**Comment by mrniko** [comment]
@monoceros RSemaphore is ready for usage :)

**Comment by monoceros** [comment]
Excellent. I'll try it.
