### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.redisson.client.handler.CommandsQueue

### ISSUE THREAD

**Issue by pyctam** [mrniko/redisson#332]
I am getting below exception, not sure why I am getting NoClassDefFoundError while I do see that class in the jar.

Using Redis redis-2.8.14 and redisson-2.2.1.jar

```java
12:03:57.631 [nioEventLoopGroup-3-7] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x6a21ec78]
java.lang.NoClassDefFoundError: Could not initialize class org.redisson.client.handler.CommandsQueue
	at org.redisson.client.RedisClient$1.initChannel(RedisClient.java:61) ~[redisson-2.2.1.jar:na]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:443) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:375) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:419) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
12:03:57.632 [nioEventLoopGroup-3-15] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x51721ff0]
java.lang.NoClassDefFoundError: Could not initialize class org.redisson.client.handler.CommandsQueue
	at org.redisson.client.RedisClient$1.initChannel(RedisClient.java:61) ~[redisson-2.2.1.jar:na]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:443) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:375) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:419) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
12:03:57.635 [nioEventLoopGroup-3-4] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x5117d5a7]
java.lang.NoClassDefFoundError: Could not initialize class org.redisson.client.handler.CommandsQueue
	at org.redisson.client.RedisClient$1.initChannel(RedisClient.java:61) ~[redisson-2.2.1.jar:na]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:443) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:375) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:419) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
12:03:57.636 [nioEventLoopGroup-3-19] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0xbb06b794]
java.lang.NoClassDefFoundError: Could not initialize class org.redisson.client.handler.CommandsQueue
	at org.redisson.client.RedisClient$1.initChannel(RedisClient.java:61) ~[redisson-2.2.1.jar:na]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:443) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:375) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:419) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
12:03:57.638 [nioEventLoopGroup-3-23] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x3a9bd525]
java.lang.NoClassDefFoundError: Could not initialize class org.redisson.client.handler.CommandsQueue
	at org.redisson.client.RedisClient$1.initChannel(RedisClient.java:61) ~[redisson-2.2.1.jar:na]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:443) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:375) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:419) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
12:03:57.640 [nioEventLoopGroup-3-11] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0xbb858dda]
java.lang.ExceptionInInitializerError: null
	at org.redisson.client.RedisClient$1.initChannel(RedisClient.java:61) ~[redisson-2.2.1.jar:na]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:443) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:375) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:419) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.21.Final.jar:4.0.21.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.IllegalArgumentException: 'promise' is already in use
	at io.netty.util.UniqueName.<init>(UniqueName.java:53) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.AttributeKey.<init>(AttributeKey.java:47) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at io.netty.util.AttributeKey.valueOf(AttributeKey.java:39) ~[netty-all-4.0.21.Final.jar:4.0.21.Final]
	at org.redisson.client.handler.CommandsQueue.<clinit>(CommandsQueue.java:41) ~[redisson-2.2.1.jar:na]
	... 13 common frames omitted
```

**Comment by mrniko** [comment]
Hi!

This class is one of main Redisson classes. Redisson can't work without it. I think you have some problems with classloader. Which environment do you use? I mean webserver and etc.

**Comment by jacohend** [comment]
I'm receiving this same error. My deps include vertx, rx, netty, java8, and I'm using the latest java 8 artifact.

**Comment by mrniko** [comment]
> java.lang.IllegalArgumentException: 'promise' is already in use

Seems another framework already bound "promise" name. Could you confirm that?
