### ISSUE TITLE
use StringCodec with config，RedissonLock.tryLock()  will occur ClassCastException

### ISSUE THREAD

**Issue by SaroLain** [mrniko/redisson#342]
Config config = new Config();
    config.setCodec(StringCodec.INSTANCE);
    ...
    RedissonClient redisson = Redisson.create(config);
    ......
    lock.tryLock();
............................

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at org.redisson.RedissonLock$1.onMessage(RedissonLock.java:95)
	at org.redisson.client.RedisPubSubConnection.onMessage(RedisPubSubConnection.java:67)
	at org.redisson.client.handler.CommandDecoder.handleMultiResult(CommandDecoder.java:263)
	at org.redisson.client.handler.CommandDecoder.decodeMulti(CommandDecoder.java:228)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:203)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:100)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)

**Comment by mrniko** [comment]
This bug was fixed since 2.2.0 version
