### ISSUE TITLE
this is a bug?I can't use RBatch。

### ISSUE THREAD

**Issue by SaroLain** [mrniko/redisson#361]
these codes will throw NullPointerException. but data has save into redis
127.0.0.1:6379[1]> keys *
1) "A3":

        Config config = new Config();
        //config.setCodec(StringCodec.INSTANCE);
        config.useSentinelServers()
                .setMasterName("mymaster")
                .setDatabase(1)
                .setMasterConnectionPoolSize(200)
                .setSlaveConnectionPoolSize(200)
                .setTimeout(6000)
                .addSentinelAddress("127.0.0.1:26379");
        RedissonClient redisson = Redisson.create(config);
        RBatch batch = redisson.createBatch();
        batch.getBucket("A1").setAsync("001");
        batch.getBucket("A2").setAsync("001");
        batch.getBucket("A3").setAsync("001");
        batch.getKeys().deleteAsync("A1");
        batch.getKeys().deleteAsync("A2");
        List result = batch.execute();

but these codes work properly.：

        redisson.getBucket("A1").setAsync("1");
        redisson.getBucket("A2").setAsync("2");
        redisson.getBucket("A3").setAsync("3");
        redisson.getKeys().deleteAsync("A1");
        redisson.getKeys().deleteAsync("A2");

io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:556)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:406)
	at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:282)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:190)
	at org.redisson.client.handler.CommandDecoder.handleCommandsDataResponse(CommandDecoder.java:136)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370)
	... 18 more
Exception in thread "main" org.redisson.client.RedisTimeoutException: Redis server response timeout during command batch execution. Channel: [id: 0xa75e9bb2, /127.0.0.1:6213 => /127.0.0.1:6379]
	at org.redisson.command.CommandBatchService$6.run(CommandBatchService.java:319)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at java.lang.Thread.run(Thread.java:745)

**Comment by SaroLain** [comment]
redis :Redis-x64-3.0.500
redisson: 2.2.4

**Comment by mrniko** [comment]
I confirm, version 2.2.4 has a bug, but current version from `master` branch doesn't has it due to RBatch enhancements in https://github.com/mrniko/redisson/commit/a95185afdd412db6883583a7c13956e71a66a0a7 commint

**Comment by xufanghui** [comment]
2016-03-02 13:34:26,692 [main] INFO  org.redisson.Version - Redisson 2.2.8
2016-03-02 13:34:26,929 [nioEventLoopGroup-2-6] INFO  org.redisson.connection.pool.SlaveConnectionPool - 5 connections initialized for /127.0.0.1:6379
2016-03-02 13:34:26,944 [nioEventLoopGroup-2-8] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last
 handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:431)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:190)
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:96)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:376)
        ... 18 more

**Comment by mrniko** [comment]
@xufanghui Could you please provide more details about how to reproduce it?

**Comment by mrniko** [comment]
@xufanghui I added logging for such kind of error. As I understand it comes from publish / subscribe channel. Please update Redisson to master branch build.
