### ISSUE TITLE
Can't init enough connections amount

### ISSUE THREAD

**Issue by hrwhat** [mrniko/redisson#375]
Caused by: org.redisson.client.RedisConnectionException: Can't init enough connections amount! from /192.168.1.87:6379
This exception  appeared sometimes.
who can tell me how to solve this problerm?
server:redis-3.0.6
client:redisson2.2.5

```java
 public Redisson getMasterSlaveClient(String addr, String hosts) {
        Config config = new Config();
        String[] hostarr = hosts.split(",");
        config.useMasterSlaveServers().setMasterAddress(addr).setLoadBalancer(
            new RandomLoadBalancer()) 
.addSlaveAddress(hostarr).setMasterConnectionPoolSize(10000).setSlaveConnectionPoolSize(
            10000).setConnectTimeout(2000);
        Redisson redisson = (Redisson)Redisson.create(config);
        return redisson;
    }
```
stacktrace:
```
Caused by: org.redisson.client.RedisConnectionException: Can't init enough connections amount! from /192.168.1.87:6379
	at org.redisson.misc.ConnectionPool$2.operationComplete(ConnectionPool.java:95)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:592)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
```

**Comment by mrniko** [comment]
I think it's network connection problem

**Comment by mrniko** [comment]
Also you can try to increase `idleConnectionTimeout` to get idle connections alive as much as you want.

**Comment by mrniko** [comment]
I have reproduced this problem. Will be fixed during this week.

**Comment by mrniko** [comment]
Fixed. Please check

**Comment by zzk1314** [comment]
My program occurs this error when i run my tomat in a Docker Container.
machine A: redis installed on host.
machine B: tomcat installed on docker container.

1.I can request the redis on machinie B host with redis-cli.
2.In machine B's tomcat container,I can request redis with telnet.
3.But my program throws this error when i start tomcat in the container.

I can't understand why i can connect redis in machine B and machine B'container, but the tomcat in container can't connect redis?

**Comment by jackygurui** [comment]
Can you confirm the step 2 and step 3 are using the same address?

**Comment by zzk1314** [comment]
@jackygurui

**Comment by zzk1314** [comment]
@jackygurui 
This is my logs and telnet command
tomcat error logs:
`
aused by: org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 10 were initialized. Server: /172.19.1.10:6379
	at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:130)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
`

machine B conatiner's command line:
`
root@d4be650a05af:/usr/local/tomcat# telnet 172.19.1.10 6379
Trying 172.19.1.10...
Connected to 172.19.1.10.
Escape character is '^]'.
`

**Comment by duqicauc** [comment]
感谢楼上给出的启发，我再去查看日志的过程中，我观察到有noSuchMethodFound的字样，因此猜测是包冲突，在解决好系统中关于netty的包冲突后，问题就没有了，非常感谢。

**Comment by EXPEbebbur** [comment]
Had similar issue with redisson 2.8.0 . Excluding Netty from redisson didn't help me. 
To fix this issue I have to explicitly include the Netty in my gradle build (compile group: 'io.netty', name: 'netty-all', version: '4.1.8.Final')
