### ISSUE TITLE
Connecting to localhost

### ISSUE THREAD

**Issue by ursbrbalaji** [mrniko/redisson#377]
Hi,

I am trying to connect to the localhost redis client as follows:
RedissonClient redisson = Redisson.create();

But I do get the following error, not sure what is the issue.

Thanks for your help.

SEVERE: Servlet.service() for servlet [XXXServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause
java.lang.NoClassDefFoundError: Could not initialize class org.redisson.codec.JsonJacksonCodec
	at org.redisson.Config.<init>(Config.java:62)
	at org.redisson.Redisson.<init>(Redisson.java:89)
	at org.redisson.Redisson.create(Redisson.java:130)
	at org.redisson.Redisson.create(Redisson.java:120)
	at .xxxx.filter.XXXFilter.doFilter(XXXFilter.java:154)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ursbrbalaji** [comment]
Version using 2.2.5

**Comment by mrniko** [comment]
Hi!

> Could not initialize class org.redisson.codec.JsonJacksonCodec
I think you don't have jackson lib in your classpath

**Comment by ursbrbalaji** [comment]
Hi,
org.redisson.codec.JsonJacksonCodec this is part of the redisson.jar right?
Or should I explicitly add any other external jar to tomcat classpath?
redisson.jar is part of WEB-INF/lib folder of the application.

Let me know if you need more info.

**Comment by ursbrbalaji** [comment]
Hi,

Finally managed to resolve the problem.
The issue was the Jackson lib in classpath was 2.1.x but redisson 2.2.5 requires 2.6.x.

**Comment by mrniko** [comment]
Yeah, the latest version~
