### ISSUE TITLE
"Can't connect to servers!" aways occured 

### ISSUE THREAD

**Issue by carlvine500** [mrniko/redisson#384]
my config as following:
jdk1.6
redisson 2.2.5

Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:91)
	at org.redisson.Redisson.<init>(Redisson.java:97)
	at org.redisson.RedissonExt.<init>(RedissonExt.java:73)
	at org.redisson.RedissonExt.create(RedissonExt.java:41)
	... 1 more

ClusterConnectionManager.java
if (lastPartitions.isEmpty()) {
            throw new RedisConnectionException("Can't connect to servers!");
 }

before if (lastPartitions.isEmpty()) ,  maybe  lastPartitions is not initialed ?

**Comment by mrniko** [comment]
Hi! lastPartitions is not initialed due to cluster info has not been acquired

**Comment by carlvine500** [comment]
I 'm sure that cluster info can be acquired .

**Comment by carlvine500** [comment]
add some log , and exception occured everytime . 

add log like this:
ClusterConnectionManager.java
String nodesValue = connection.sync(RedisCommands.CLUSTER_NODES);
+ log.info("redis cluster info:" + nodesValue);

 test case:
	public static void main(String[] args) throws Exception {
		Config config = new Config();
		config.useClusterServers().addNodeAddress("10.58.52.63:6379");
		final RedissonClient redisson = Redisson.create(config);
	}

exception:
[main] INFO org.redisson.cluster.ClusterConnectionManager - redis cluster info:e81fbe69e04673b5c3a4ae71985b2213b3f8cdc7 10.58.52.63:6379 myself,master - 0 0 0 connected 0-16383

Exception in thread "main" org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:99)
	at org.redisson.Redisson.<init>(Redisson.java:98)
	at org.redisson.Redisson.create(Redisson.java:131)
	at Test.main(Test.java:14)
[nioEventLoopGroup-2-6] INFO org.redisson.cluster.ClusterConnectionManager - master: //10.58.52.63:6379 added for slot ranges: [[0-16383]]

**Comment by mrniko** [comment]
I have just runned my test with follow settings:
```java
    Config config = new Config();
    config.useClusterServers().addNodeAddress("127.0.0.1:7004");
    RedissonClient redisson = Redisson.create(config);
```

Here is my log output:

```
13:37:17 [nioEventLoopGroup-2-8] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [//127.0.0.1:7002] added for slot ranges: [[10923-16383]]
13:37:17 [nioEventLoopGroup-2-7] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [//127.0.0.1:7004] added for slot ranges: [[5461-10922]]
13:37:17 [nioEventLoopGroup-2-15] INFO org.redisson.cluster.ClusterConnectionManager - slaves: [//127.0.0.1:7003] added for slot ranges: [[0-5460]]
13:37:17 [nioEventLoopGroup-2-8] INFO org.redisson.cluster.ClusterConnectionManager - master: //127.0.0.1:7005 added for slot ranges: [[10923-16383]]
13:37:17 [nioEventLoopGroup-2-13] INFO org.redisson.cluster.ClusterConnectionManager - master: //127.0.0.1:7001 added for slot ranges: [[5461-10922]]
13:37:17 [nioEventLoopGroup-2-2] INFO org.redisson.cluster.ClusterConnectionManager - master: //127.0.0.1:7000 added for slot ranges: [[0-5460]]
13:37:18 [nioEventLoopGroup-2-10] INFO org.redisson.cluster.ClusterConnectionManager - [[0-5460]] slots found to add
Adding requests to queue...

Queued all 1 000 000 produce UID requests.

Memory Status: [Used: 69 MB (1% of max),  Free: 176 MB (4% of max),  Total: 245 MB (6% of max),  Max: 3 614 MB]
     0% complete.         1 414 of 1 000 000 attempted.  1 691 per sec.         0,0 min elapsed.         9,9 min remaining(est).             0 errors.
     6% complete.        62 707 of 1 000 000 attempted.  3 961 per sec.         0,3 min elapsed.         3,9 min remaining(est).             0 errors.
    13% complete.       128 027 of 1 000 000 attempted.  4 153 per sec.         0,5 min elapsed.         3,5 min remaining(est).             0 errors.
    19% complete.       192 270 of 1 000 000 attempted.  4 195 per sec.         0,8 min elapsed.         3,2 min remaining(est).             0 errors.
```

Also please note, that minimal cluster masters amount should be 3 it's requirement from Redis cluster spec.

**Comment by carlvine500** [comment]
thanks !  
suggest redisson support single redis-cluster node or adding a error log  if connect to a single redis-cluster node .
because in personal computer, we alwayls test redis with single redis-cluster node .

**Comment by mrniko** [comment]
@carlvine500  Does it work now?

**Comment by carlvine500** [comment]
"Can't connect to servers!" some times occured 
**version:**  redisson-2.2.9 
**redis cluster info:**
4bf50ab6e2407a4c82cb66ee8b716ae55368dcba 10.58.56.157:8303 master - 0 1457492577535 17 connected 8192-16383
9eafc1008687d547e5ba1a50c354b36fe8ce3e2c 10.58.56.157:8302 master - 0 1457492575527 16 connected 1-8191
a6b8afe741422c95c6e03a68ba44b131e0749d51 10.58.56.157:8332 myself,master - 0 0 19 connected 0

**exception:**
Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
	at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:99) ~[redisson-2.2.9.jar!/:na]
	at org.redisson.Redisson.<init>(Redisson.java:100) ~[redisson-2.2.9.jar!/:na]
	at org.redisson.RedissonExt.create(RedissonExt.java:77) ~[redisson-ext-1.0.0-SNAPSHOT.jar!/:na]

**Comment by carlvine500** [comment]
MasterSlaveConnectionManager.java
maybe lastPartitions is not  async  inited  before  exception("Can't connect to servers!")

**Comment by mrniko** [comment]
lastPartitions initialized synchronous, take at line `masterFuture.syncUninterruptibly();` Please check your "Can't connect to servers!" exception details because it has last cause of error.

**Comment by carlvine500** [comment]
"Can't connect to servers!" sometimes occured .
**this is my  exception log from my code to redisson:**
Caused by: java.lang.IllegalStateException: RedissonExt Exception,businessName=PG_TRADING_USER_CART_LOCK,redis nodes(host1:port1,host2:port2...)=[10.58.56.157:8332, 10.58.56.157:8302, 10.58.56.157:8303]
at org.redisson.RedissonExt.create(RedissonExt.java:83) ~[redisson-ext-1.0.0-SNAPSHOT.jar!/:na]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
... 63 common frames omitted
Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:99) ~[redisson-2.2.9.jar!/:na]
at org.redisson.Redisson.<init>(Redisson.java:100) ~[redisson-2.2.9.jar!/:na]
at org.redisson.RedissonExt.create(RedissonExt.java:77) ~[redisson-ext-1.0.0-SNAPSHOT.jar!/:na]
... 68 common frames omitted

**Comment by mrniko** [comment]
scroll down the exception log

**Comment by carlvine500** [comment]
**full log frames  ,some frames still omitted:**

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cartLock' defined in class path resource [conf/spring/AC-beans.xml]: Bean instantiation via factory method
 failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.RedissonExt]: Factory method 'create' threw exception; nested exception is java.lang.I
llegalStateException: RedissonExt Exception,businessName=PG_TRADING_USER_CART_LOCK,redis nodes(host1:port1,host2:port2...)=[10.xx.56.157:8332, 10.xx.56.157:8302, 10.xx.56.157:8303]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1119) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1014) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:461) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:435) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:559) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:169) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:305) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 48 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.RedissonExt]: Factory method 'create' threw exception; nested exception is java.lang.IllegalStateException: RedissonExt Exception,businessName=PG_TRADING_USER_CART_LOCK,redis nodes(host1:port1,host2:port2...)=[10.xx.56.157:8332, 10.xx.56.157:8302, 10.xx.56.157:8303]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:xx8) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 62 common frames omitted
Caused by: java.lang.IllegalStateException: RedissonExt Exception,businessName=PG_TRADING_USER_CART_LOCK,redis nodes(host1:port1,host2:port2...)=[10.xx.56.157:8332, 10.xx.56.157:8302, 10.xx.56.157:8303]
        at org.redisson.RedissonExt.create(RedissonExt.java:83) ~[redisson-ext-1.0.0-SNAPSHOT.jar!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        ... 63 common frames omitted
Caused by: org.redisson.client.RedisConnectionException: Can't connect to servers!
        at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:99) ~[redisson-2.2.9.jar!/:na]
        at org.redisson.Redisson.<init>(Redisson.java:100) ~[redisson-2.2.9.jar!/:na]
        at org.redisson.RedissonExt.create(RedissonExt.java:77) ~[redisson-ext-1.0.0-SNAPSHOT.jar!/:na]
        ... 68 common frames omitted
2016-03-08 21:08:15.135 [INFO ] [main]   c.a.dubbo.registry.zookeeper.ZookeeperRegistry.unsubscribe(AbstractRegistry.java:372) -  [DUBBO] Unsubscribe: consumer://10.xx.56.114/com.gome.pangu.virtual.dubbo.service.VirtualEncryptedService?application=com.gome.pangu_pangu-trading-web&category=providers,configurators,routers&default.check=false&dubbo=2.5.5.g1-SNAPSHOT&interface=com.gome.pangu.virtual.dubbo.service.VirtualEncryptedService&loadbalance=random&logger=slf4j&methods=encryptedPassword&pid=369&position=cart&revision=1.0&side=consumer&timestamp=1457442493853&version=1.0, dubbo version: 2.5.5.g1-SNAPSHOT, current host: 10.xx.56.114
2016-03-08 21:08:15.135 [INFO ] [main]   c.a.dubbo.registry.zookeeper.ZookeeperRegistry.unsubscribe(AbstractRegistry.java:372) -  [DUBBO] Unsubscribe: consumer://10.xx.56.114/com.gome.pangu.virtual.dubbo.service.XyQueryService?application=com.gome.pangu_pangu-trading-web&category=providers,configurators,routers&check=false&default.check=false&dubbo=2.5.5.g1-SNAPSHOT&interface=com.gome.xx.yy.dubbo.service.VirtualQueryService&loadbalance=random&logger=slf4j&methods=findVirtualAccountHistory,findVirtualAccountByPassword,findVirtualAccountByUserId&pid=369&position=cart&revision=1.0&side=consumer&timestamp=1457442492768&version=1.0, dubbo version: 2.5.5.g1-SNAPSHOT, current host: 10.xx.56.114

**Comment by shichanglin5** [comment]
May be same issue i encounterd! 
I modified code to output exception stack and compile locally 
<img width="907" alt="image" src="https://github.com/user-attachments/assets/c4772099-d12b-433a-a899-b198d56868de">

this issue seems like related to netty: https://github.com/netty/netty/issues/12842
exception log as follows:
```log
2024-07-20 13:01:39.400 [main] INFO  org.redisson.Version - Redisson 3.20.1
2024-07-20 13:01:44.634 [main] ERROR org.redisson.connection.ReplicatedConnectionManager - Can't connect to redis://arex-demo-arex-redis.arex-demo.svc.cluster.local:6379
java.util.concurrent.CompletionException: org.redisson.client.RedisConnectionException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'arex-demo-arex-redis.arex-demo.svc.cluster.local' [A(1), AAAA(28)] and search domain query for configured domains failed as well: [arex-demo.svc.cluster.local, svc.cluster.local, cluster.local]
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
	at org.redisson.client.RedisClient.lambda$resolveAddr$0(RedisClient.java:207) ~[redisson-3.20.1.jar!/:3.20.1]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.112.Final.jar!/:4.1.112.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) ~[netty-common-4.1.112.Final.jar!/:4.1.112.Final]
```

**Comment by mrniko** [comment]
@shichanglin5 

Fixed
