### ISSUE TITLE
Sentinel error when no slaves

### ISSUE THREAD

**Issue by a1u** [mrniko/redisson#391]
```
Config config = new Config();
config.useSentinelServers()
    .setMasterName("mymaster")
    .addSentinelAddress("127.0.0.1:26389");
Redisson redisson = Redisson.create(config);
```

if there are no slaves on SentinelConnectionManager:82 we have a List<Map<String, String>> sentinelSlaves = connection.sync(StringCodec.INSTANCE, RedisCommands.SENTINEL_SLAVES, cfg.getMasterName()); which returns just Map not List of Maps.
So, the exception I get is:
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
	... 41 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.redisson.RedissonClient]: Factory method 'redissonClient' threw exception; nested exception is java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.List
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 53 more
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.List
	at org.redisson.connection.SentinelConnectionManager.<init>(SentinelConnectionManager.java:82)
	at org.redisson.Redisson.<init>(Redisson.java:96)
	at org.redisson.Redisson.create(Redisson.java:131)
	at com.atl.csc.conf.RedisConfig.redissonClient(RedisConfig.java:122)

You may argue that it is not correct if there are no slaves, but, this cut config is used on test machines and not on production (which is fully configured with slaves). So, would be nice to handle this error.
Thanks.

**Comment by a1u** [comment]
redis v.3.0.3
redisson 2.2.6

**Comment by mrniko** [comment]
@a1u Do you really use 2.2.6 version?
Because i have another error in this case:

```java
org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 5 were initialized. Server: /127.0.0.1:6399
	at org.redisson.misc.ConnectionPool$2.operationComplete(ConnectionPool.java:95)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:592)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: no further information: /127.0.0.1:6399
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	... 3 more

```

**Comment by a1u** [comment]
yes:
```
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson</artifactId>
            <version>2.2.6</version>
        </dependency>
```

I have one master on 6379 and one sentinel on 26379.
On 26379 redis-cli SENTINEL SLAVES mymaster shows (empty list or set)

**Comment by mrniko** [comment]
Fixed

**Comment by a1u** [comment]
many thanks

**Comment by YangZhong** [comment]
2.2.8 has the problem. Reverting to 2.2.7 resolves that.

    final Config  config = new Config();
    config.useSingleServer()
      .setAddress( address)
      .setPassword( p);
    Redisson.create( config);

org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 1 from 5 were initialized. Server: ...:6379
at org.redisson.connection.pool.ConnectionPool$2.operationComplete(ConnectionPool.java:112)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:593)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
at java.lang.Thread.run(Thread.java:745)

Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: ...:6379
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:220)
at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
... 5 more

**Comment by mrniko** [comment]
@YangZhong Can't reproduce it with 2.2.8

**Comment by amosli** [comment]
redis:3.0.7
redisson: 2.2.9
gradle:  compile 'org.redisson:redisson:2.2.9'
android:4.3
find this problem too!
config:
` 
   public final int TIMEOUT = 5000;
    public final int POOLSIZE = 1000;
  Config config = new Config();
      config.useSingleServer().setAddress("192.168.0.42:6379").setConnectionPoolSize(POOLSIZE).setTimeout(TIMEOUT).setConnectTimeout(TIMEOUT);
        redisson = Redisson.create(config);
      `

org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 5 were initialized. Server: /192.168.0.42:6379

How to solve it ? Thanks for help.

**Comment by mrniko** [comment]
@amosli scroll down your exception stack, Redisson can't connect to your Redis server

**Comment by Abeer-Brery** [comment]
Using version 2.2.7
RedissonClient redisson = Redisson.create(); 
I have the same Exception, what should I do?

Exception in thread "main" org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 5 were initialized. Server: /127.0.0.1:6379
	at org.redisson.connection.pool.ConnectionPool$2.operationComplete(ConnectionPool.java:112)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:593)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment]
Have you checked your connection with this server?

**Comment by Abeer-Brery** [comment]
I checked it, now it is working ...
Thank you.

**Comment by Abeer-Brery** [comment]
In my program, I try to store data in hash-map and retrieve it.
The data is stored in 500*5 separated hashes each with maximum 9 fields, I make this by loop.
if I increase more than this, I have the following exception.

`Exception in thread "main" org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 5 were initialized. Server: /127.0.0.1:6379
	at org.redisson.connection.pool.ConnectionPool$2.operationComplete(ConnectionPool.java:112)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:593)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.redisson.client.RedisConnectionException: RedisConnection [redisClient=[addr=/127.0.0.1:6379], channel=[id: 0xf9cda152, 0.0.0.0/0.0.0.0:50649 :> /127.0.0.1:6379]] is not active!
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:260)
	at org.redisson.connection.pool.ConnectionPool.access$300(ConnectionPool.java:43)
	at org.redisson.connection.pool.ConnectionPool$3.operationComplete(ConnectionPool.java:219)
	... 7 more`
Do I need more servers or what should be the problem?

**Comment by mrniko** [comment]
Does this problem rises at app startup only?

**Comment by Abeer-Brery** [comment]
I think it because every iteration I create a new connection to the server.

**Comment by mrniko** [comment]
How do you make it? could you provide code?

**Comment by Abeer-Brery** [comment]
In the loop, I call a method which have this line
RedissonClient redisson = Redisson.create(); 
So as number of iteration, as number of this line executed.

**Comment by mrniko** [comment]
This is a bad idea. Share Redisson instances with same config

**Comment by Abeer-Brery** [comment]
yes I know, I wasn't taking my care.
I fixed it but I have the same exception, and I think there is a problem with the server
because it shows
> Error registering fd event for the new client: 
> ult too large
and continuing processing this

**Comment by mrniko** [comment]
RedisConnection [redisClient=[addr=/127.0.0.1:6379], channel=[id: 0xf9cda152, 0.0.0.0/0.0.0.0:50649 :> /127.0.0.1:6379]] is not active!

As I see the reason may be then you behind some firewall and it has an opened port but connection is not alive.

**Comment by mrniko** [comment]
@vchau 
> Can you comment on whether you will change the behavior to work for 1-sentinel/1-redis setup? 

Currently this task has low priority. But anyway you contribute this change to project.

**Comment by srivallig** [comment]
Helo,

I started using redis with my tomcat 8 to store sessions.
configuration : java1.8, tomcat 8, Redis version /redis-3.2.8,Redission 3.3.1

i am on windows environment so i am using vagrant virtual box with ubuntu.
i installed redis in this using below ones

$ wget http://download.redis.io/releases/redis-3.2.8.tar.gz
$ tar xzf redis-3.2.8.tar.gz
$ cd redis-3.2.8
$ make
$sudo apt-get install redis-server
$sudo service redis-server restart
$sudo service redis-server status   -- server running only

my server is running in Virtual box and in my eclipse MARs i setup my workspace
in my tomcat8/lib i copied redis-session-manager-with-dependencies-2.1.1-SNAPSHOT.jar
and redission-3.3.1.jar as per below link
https://github.com/chexagon/redis-session-manager

in context.xml   - added below
<Manager className="com.crimsonhexagon.rsm.redisson.SingleServerSessionManager"
    endpoint="localhost:6379"
    sessionKeyPrefix="_rsm_"
    saveOnChange="false"
    forceSaveAfterRequest="false"
    dirtyOnMutation="false"
    ignorePattern=".*\\.(ico|png|gif|jpg|jpeg|swf|css|js)$"
    connectionPoolSize="100"
    database="0"
    password="redispwd"
    timeout="60000"
    pingTimeout="1000"
    retryAttempts="20"
    retryInterval="1000"
/>

when i tried to start my tomcat i am getting below error, could any one please help me to resolve this issue? really waiting for response as i am new to this one?

Mar 15, 2017 12:41:11 PM com.crimsonhexagon.rsm.RedisSessionManager startInternal
SEVERE: Unable to load serializer
org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 10 were initialized. Server: localhost/127.0.0.1:6379
	at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:130)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:98)
	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:298)
	at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:53)
	at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:268)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:98)
	at org.redisson.connection.ClientConnectionsEntry$1.operationComplete(ClientConnectionsEntry.java:141)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:98)
	at org.redisson.client.RedisClient$2$2.run(RedisClient.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	... 3 more

**Comment by srivallig** [comment]
in my context.xml i aded below
<Manager className="com.crimsonhexagon.rsm.redisson.SingleServerSessionManager"
    endpoint="localhost:6379"
    sessionKeyPrefix="_rsm_"
    saveOnChange="false"
    forceSaveAfterRequest="false"
    dirtyOnMutation="false"
    ignorePattern=".*\\.(ico|png|gif|jpg|jpeg|swf|css|js)$"
    connectionPoolSize="100"
    database="0"
    password="redispwd"
    timeout="60000"
    pingTimeout="1000"
    retryAttempts="20"
    retryInterval="1000"
/>

**Comment by srivallig** [comment]
Hi mrniko ,
i have in this tomcat context xml 
Manager className="com.crimsonhexagon.rsm.redisson.SingleServerSessionManager"
    endpoint="localhost:6379"
    sessionKeyPrefix="_rsm_"
    saveOnChange="false"
    forceSaveAfterRequest="false"
    dirtyOnMutation="false"
    ignorePattern=".*\\.(ico|png|gif|jpg|jpeg|swf|css|js)$"
    connectionPoolSize="100"
    database="0"
    password="redispwd"
    timeout="60000"
    pingTimeout="1000"
    retryAttempts="20"
    retryInterval="1000"


Could you please elaborate regarding connection check  ?

**Comment by mrniko** [comment]
Connection could be checked using redis-cli tool. Run it on the same host you using for tomcat. Just wondering why can't you use Redisson's Tomcat Manager instead?

**Comment by srivallig** [comment]
redis 127.0.0.1:6379> ping
PONG

 i am getting response using redis client means redis is connected right?

**Comment by mrniko** [comment]
Did you run it on the same instance there tomcat deployed?

**Comment by srivallig** [comment]
my tomcat deployed in windows localhost with port 8081
as i mentioned earlier i am running redis in vagrant virtual box from windows , so tested this redis client in that VB

**Comment by mrniko** [comment]
you should run `redis-cli` on windows host instead

**Comment by srivallig** [comment]
I found  way to install Redis under Windows
Download the latest Redis .msi file from
https://github.com/MSOpenTech/redis/releases

Then only i can run redis-cli on windows host right?
could you plesae give an article/link to get me full length understanding in real time  configuration leavel as i followed few internet posts and did installation , am not sure am i foloowing correct way as iam stuck with many issues ? 

My reqquirement is in real prodcution env, repliacting many nodes with redis to server n number of clients so to try this from local machine i started with my tomcat node still i could not achieve it so please suggest any link /video/tutorial  to resolve my setup issue ?

one more thing is what is the best way to work with redis in windows environment 
1) using linux VB 
2) Download the latest Redis .msi file from https://github.com/MSOpenTech/redis/releases

please guide me through

**Comment by srivallig** [comment]
sorry for the typo mistakes

**Comment by mrniko** [comment]
I wouldn't recommend you to use redis built for windows, because it's not recommended for production usage. Run both Redis and Tomcat using VB
