### ISSUE TITLE
Sentinel "ERR unknown command 'AUTH'" error after upgrade from 2.2.5 to 2.2.6,2.2.7

### ISSUE THREAD

**Issue by emoseman** [mrniko/redisson#393]
```java
 Config config = new Config();
            config.useSentinelServers()
                  .setRetryInterval(redisReconnectDelay.get())
                  .setMasterConnectionPoolSize(redisConnectionPoolSize.get())
                  .setTimeout(redisTimeout.get())
                  .setRetryAttempts(redisRetryCount.get())
                  .setSlaveConnectionPoolSize(redisConnectionPoolSize.get())
                  .setPassword(redisPassword)
                  .setMasterName(redisMasterName.get());

            // Add sentinel server addresses
            for (String sentinelServerAddress : redisSentinelServers.get().split("\\s*,\\s*")) {
                config.useSentinelServers().addSentinelAddress(sentinelServerAddress);
            }

 ...
 redisson = Redisson.create(config);
```

**Stacktrace:**
```java
11:53:31.747-main-INFO o.r.Version:42 - Redisson 2.2.7

org.redisson.client.RedisException: ERR unknown command 'AUTH'. channel: [id: 0xfa3297ed, /192.168.0.2:55117 => redis01.ops.aol.com/192.168.0.3:26379] command: CommandData [promise=DefaultPromise@4b8a3643(incomplete), command=(AUTH), params=[PASSWORD_REMOVED], codec=null]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:190)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:105)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:376)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
11:53:32.049-main-ERROR c.a.u.RedisConnectionProvider:184 - ERR unknown command 'AUTH'. channel: [id: 0xfa3297ed, /192.168.0.2:55117 => redis01.ops.aol.com/192.168.0.3:26379] command: CommandData [promise=DefaultPromise@4b8a3643(incomplete), command=(AUTH), params=[PASSWORD_REMOVED], codec=null]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.RuntimeException: Failed to connect to redis sentinel servers redis01.ops.aol.com:26379,redis02.ops.aol.com:26379,redis03.ops.aol.com:26379
	at com.aol.util.RedisConnectionProvider.connect(RedisConnectionProvider.java:194)
	at com.aol.util.RedisConnectionProvider.config(RedisConnectionProvider.java:129)
	at com.aol.util.RedisConnectionProvider.getInstance(RedisConnectionProvider.java:92)
	at com.aol.ido.aws.config.ServiceConfig.<init>(ServiceConfig.java:82)
	at com.aol.ido.aws.TestBase.<clinit>(TestBase.java:153)
	... 25 more
```

**Comment by mrniko** [comment]
Will check that

**Comment by mrniko** [comment]
Fixed
