### ISSUE TITLE
Read all values of set

### ISSUE THREAD

**Issue by ursbrbalaji** [mrniko/redisson#403]
Hi,
When I am trying to read all the values of set I get the following exception. Let me know if you require more details.

Version: 2.2.7

Code:
RSet<String> set = redisson.getSet(setname);
Set<String> members = set.readAll();

Exception in thread "main" org.redisson.client.RedisException: Unexpected exception while processing command
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:222)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:88)
	at org.redisson.RedissonObject.get(RedissonObject.java:49)
	at org.redisson.RedissonSet.readAll(RedissonSet.java:154)
	at RedisHelper.getMembersOfSet(RedisHelper.java:218)
	at RedisHelper.main(RedisHelper.java:596)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'png': was expecting ('true', 'false' or 'null')
 at [Source: io.netty.buffer.ByteBufInputStream@6bbd4bac; line: 1, column: 7]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3451)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2610)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:841)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:737)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2796)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:68)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:201)
	at org.redisson.client.handler.CommandDecoder.decodeMulti(CommandDecoder.java:220)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:210)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:105)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:376)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Feb 11, 2016 5:18:26 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:431)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.redisson.client.handler.CommandDecoder.decoder(CommandDecoder.java:317)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:201)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:96)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:376)
	... 18 more

**Comment by mrniko** [comment]
Hi!

Could you please provide a test case? Because Redisson passes tests for `RSet.readAll` method.

**Comment by mrniko** [comment]
Anyway easy to assume that error cause is in incorrect data format stored in Redis `Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'png': was expecting ('true', 'false' or 'null')`

**Comment by ursbrbalaji** [comment]
Actually the issue is happening if I store the data to redis via redis-cli and try to retrieve the data from Java Code.

**Comment by ursbrbalaji** [comment]
Later I noticed that the data stored via Java code is stored with escape characters as "\"png\"" whereas when directly stored from command line is stored only with quotes as "png"

**Comment by mrniko** [comment]
so it's clear that you have store data in wrong json format isn't it?

**Comment by ursbrbalaji** [comment]
I added the data to the set as follows:
sadd myset "png"
http://redis.io/commands/sadd

**Comment by mrniko** [comment]
in json all strings should be wrapped by ", so "png" should be written as "\"png\""

**Comment by ursbrbalaji** [comment]
Ok sure. thank you

**Comment by cmhsu-cs** [comment]
I have the same issue did you figure this out? @ursbrbalaji

**Comment by luoming1224** [comment]
> Actually the issue is happening if I store the data to redis via redis-cli and try to retrieve the data from Java Code.

redisson use JsonJacksonCodec default,it should use StringCodec in this case;

    Config redisConfig = new Config();
    redisConfig..setCodec(new StringCodec()).useSingleServer().setAddress(redisUrl);

**Comment by mrniko** [comment]
@luoming1224 

It uses FSTCodec by default since 3.10.0 version
