### ISSUE TITLE
ElasticacheCluster not working correctly with DistributedLocks

### ISSUE THREAD

**Issue by sinusekhar** [mrniko/redisson#409]
I am trying to use redisson 2.2.7 for distributed locks. I have a 3 node Elasticache cluster with one of them as master.

When I try to get lock using the following code, i get an error saying that i cant write to a Slave. My assumption is that i can feed a list of nodes to the redisson client as Elasticache nodes and it will figure out who the master is...is that not true?

```
if (RLockVariable.tryLock(waitTimeInSeconds,leaseTimeInSeconds, TimeUnit.SECONDS)) {
                    //Do something
                }
```

The error that i get is shown below..

```
Caused by: com.lambdaworks.redis.RedisException: READONLY You can't write against a read only slave.
        at com.lambdaworks.redis.protocol.Command.complete(Command.java:76)
        at com.lambdaworks.redis.protocol.CommandHandler.decode(CommandHandler.java:77)
        at com.lambdaworks.redis.protocol.CommandHandler.channelRead(CommandHandler.java:52)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)

```

Here is how i am setting up a redisson client

            StringTokenizer nodes = new StringTokenizer(nodeList, DELIMITER);

            Config config = new Config();
            while(nodes.hasMoreTokens()) {
                config.useElasticacheServers().addNodeAddress(nodes.nextToken());
            }
            config.useElasticacheServers().setScanInterval(scanInterval);

            redissonClient = Redisson.create(config);

**Comment by mrniko** [comment]
It seems like you using old version of Redisson, because it has `com.lambdaworks.redis.protocol.Command` object. `com.lambdaworks` was removed since 2.x.x version. So check your classpath.

**Comment by sinusekhar** [comment]
Thank you, it was a problem with my build that was continuing to use the old version. I really appreciate you taking a look at it.

**Comment by mrniko** [comment]
You're welcome!
