### ISSUE TITLE
An exception was thrown by org.redisson.RedissonLock$8$1.operationComplete()- java.lang.NullPointerException

### ISSUE THREAD

**Issue by AlexFastAll** [mrniko/redisson#423]
An exception was thrown by org.redisson.RedissonLock$8$1.operationComplete()
java.lang.NullPointerException
	at org.redisson.RedissonLock$8$1.operationComplete(RedissonLock.java:580)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise$LateListeners.run(DefaultPromise.java:854)
	at io.netty.util.concurrent.DefaultPromise$LateListenerNotifier.run(DefaultPromise.java:882)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

in class RedissonLock ,row 580, futureRef.get() may be null

**Comment by mrniko** [comment]
Fixed
