### ISSUE TITLE
RedisConnectionException: Can't init enough connections

### ISSUE THREAD

**Issue by Master-chan** [mrniko/redisson#431]
Redisson version: all from 2.2.3 to 2.2.9
Redis version: 3.0.4
Initializaition:
```java
redissonConfig
.useSingleServer()
.setAddress(config.getSingleAdress())
.setPassword(config.getPassword())
.setDatabase(REDIS_DATABASE)
.setConnectionPoolSize(2);
client = Redisson.create(redissonConfig);
```

```
internal.redisson.client.RedisConnectionException: Can't init enough connections
 amount! 5 from 5 was initialized. Server: /xxx.xxx.xxx.xxx:xxxx
        at internal.redisson.misc.ConnectionPool.initConnections(ConnectionPool.
java:78) ~[?:?]
        at internal.redisson.misc.ConnectionPool.add(ConnectionPool.java:63) ~[?
:?]
        at internal.redisson.connection.SingleEntry.setupMasterEntry(SingleEntry
.java:57) ~[?:?]
        at internal.redisson.connection.SingleConnectionManager.initEntry(Single
ConnectionManager.java:87) ~[?:?]
        at internal.redisson.connection.MasterSlaveConnectionManager.init(Master
SlaveConnectionManager.java:171) ~[?:?]
        at internal.redisson.connection.MasterSlaveConnectionManager.<init>(Mast
erSlaveConnectionManager.java:129) ~[?:?]
        at internal.redisson.connection.SingleConnectionManager.<init>(SingleCon
nectionManager.java:45) ~[?:?]
        at internal.redisson.Redisson.<init>(Redisson.java:85) ~[?:?]
        at internal.redisson.Redisson.create(Redisson.java:122) ~[?:?]
```

**Comment by mrniko** [comment]
Oh, my bad, connectionPoolSize is lower than default initConnectionPoolSize = 5.

**Comment by Master-chan** [comment]
Will .setConnectionPoolSize(5) temporarily fix the problem?

**Comment by mrniko** [comment]
Fixed
