### ISSUE TITLE
Connection pool exhausted! All connections are busy

### ISSUE THREAD

**Issue by carlvine500** [mrniko/redisson#438]
version: redisson-2.2.9
**test as following:**
```
public static void main(String[] args) throws Exception {
		Config config = new Config();
		config.useClusterServers().setReadMode(ReadMode.MASTER)//
				// .setSubscriptionsPerConnection(1024)//
				.setMasterConnectionMinimumIdleSize(2)//
				.setSlaveConnectionMinimumIdleSize(2)//
				.setMasterConnectionPoolSize(1024)//
				.setSlaveConnectionPoolSize(1024)//
				.setTimeout(2000)//
				.addNodeAddress("10.58.56.157:8300");
		RedissonClient redisson = Redisson.create(config);
		for (int i = 0; i < 10240; i++) {
			System.out.println(i);
			RTopic<Object> topic = redisson.getTopic("test" + i);
			topic.addListener(new MessageListener<Object>() {
				@Override
				public void onMessage(String channel, Object msg) {
					System.out.println("channel=" + channel + ",msg=" + msg);
				}
			});
		}
	}

```
**exception:**
0
1
2
3
4
......
124
125
Exception in thread "main" org.redisson.client.RedisConnectionException: Connection pool exhausted! All connections are busy. Try to increase connection pool size. Hosts with fully busy connections: [/10.58.56.157:8301]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:164)
	at org.redisson.connection.pool.PubSubConnectionPool.get(PubSubConnectionPool.java:26)
	at org.redisson.connection.SingleEntry.nextPubSubConnection(SingleEntry.java:75)
	at org.redisson.connection.MasterSlaveConnectionManager.nextPubSubConnection(MasterSlaveConnectionManager.java:653)
	at org.redisson.connection.MasterSlaveConnectionManager.connect(MasterSlaveConnectionManager.java:416)
	at org.redisson.connection.MasterSlaveConnectionManager.subscribe(MasterSlaveConnectionManager.java:410)
	at org.redisson.connection.MasterSlaveConnectionManager.subscribe(MasterSlaveConnectionManager.java:363)
	at org.redisson.RedissonTopic.addListener(RedissonTopic.java:81)
	at org.redisson.RedissonTopic.addListener(RedissonTopic.java:77)
	at org.redisson.RedisssonBugOfConnectionLimitTest.main(RedisssonBugOfConnectionLimitTest.java:23)

**Comment by carlvine500** [comment]
maybe this Exception was cause by SingleServerConfig.subscriptionConnectionPoolSize=25

we can avoid exception by  Config.useClusterServers().setSubscriptionsPerConnection(1024)

**Comment by mrniko** [comment]
by default `subscriptionConnectionPoolSize=25` and `subscriptionsPerConnection=5`. Maximum subscription topics amount with default settings is `25*5 = 125`. In your case you are trying subscribe to 10240 topics. So you should set `subscriptionsPerConnection` at least to `410` value.

Anyway I will fix an error string in this case.

**Comment by carlvine500** [comment]
subscriptionConnectionPoolSize=25 should expose to users ?  
or  add a variable subscriptionMaxConnectionPoolSize , because We don't know how many conn application needed . 
subscriptionsPerConnection too max will effect performance ?

**Comment by jackygurui** [comment]
@carlvine500 I think each subscribe command occupies a connection, you may want to code your application in such a way that you don't subscribe to the same channel/topic multiple times.

**Comment by mrniko** [comment]
> subscriptionConnectionPoolSize=25 should expose to users ?

Sorry, I didn't get you. `subscriptionConnectionPoolSize` setting already exposed through Config object param.

> subscriptionsPerConnection too max will effect performance ?
Depends on message amount sending through a subscription.

**Comment by carlvine500** [comment]
cluster can't set subscriptionConnectionPoolSize : 
org.redisson.Config.useClusterServers().subscriptionConnectionPoolSize (..) ?

**Comment by mrniko** [comment]
In case of cluster server this setting named `slaveSubscriptionConnectionPoolSize`

**Comment by carlvine500** [comment]
I am confused by slaveSubscriptionConnectionPoolSize or "subscriptionConnectionPoolSize" ,
"subscriptionConnectionPoolSize"  is better .

**Comment by mrniko** [comment]
According Redisson documentation https://github.com/mrniko/redisson/wiki/2.-configuration#241-cluster-settings
