### ISSUE TITLE
Need suggestion for connection issue

### ISSUE THREAD

**Issue by elebelesam** [mrniko/redisson#465]
Hi,

I am using a single server connection and set the connection pool size to 10. I have created multiple threads to test a code snippet where I am saving an object to RBucket<> object and deleting it afterwards in a same transaction block. I get following error sometime in the process, 

Exception in thread "51" org.redisson.client.RedisConnectionException: Can't init enough connections amount! Only 0 from 5 were initialized. Server: /127.0.0.1:6379
	at org.redisson.connection.pool.ConnectionPool$2.operationComplete(ConnectionPool.java:112)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
	at io.netty.util.concurrent.DefaultPromise$2.run(DefaultPromise.java:593)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

Any suggestion?

Thanks.

**Comment by mrniko** [comment]
Hi,

Please, check your network connection with Redis. Is it behind proxy?

**Comment by elebelesam** [comment]
Hi,

Redis server is running. I can connect a client to the server using terminal.

Some thread can execute without any problem. few threads get this error. Could you please explain why this error may happen? I just want to verify the code will run synchronously without any error.

Thanks.

**Comment by elebelesam** [comment]
Hi,

Also it was not behind the proxy, I was running the program using eclipse.

Thanks.

**Comment by mrniko** [comment]
This issue appears during Redisson instance creation

**Comment by elebelesam** [comment]
Do you have any example how to deal with Redisson instance creation when multiple threads are trying to get the connection?

**Comment by jackygurui** [comment]
Are you sharing one redisson instance between threads or are you creating one for each thread?

**Comment by elebelesam** [comment]
One for each thread. Is this the rite way of doing it? 

Is there any ConnectionPool class in Redisson that I can use to get the connection from?

Looking for your suggestion.

**Comment by elebelesam** [comment]
The intended per thread execution is,

get Redisson connection
Do task
close the connection

**Comment by jackygurui** [comment]
The Redisson instance itself is thread safe, you can try and share it across threads.

**Comment by elebelesam** [comment]
Hi,

When the following error supposed to be occured?

org.redisson.client.RedisException: Unexpected exception while processing command
at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:222)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:88)
	at org.redisson.RedissonObject.get(RedissonObject.java:49)
	at org.redisson.RedissonBucket.trySet(RedissonBucket.java:147)

Caused by: java.lang.IllegalStateException: Redisson is shutdown
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:357)
	at org.redisson.command.CommandAsyncService.writeAsync(CommandAsyncService.java:346)
	at org.redisson.RedissonBucket.trySetAsync(RedissonBucket.java:142)

Thanks.

**Comment by mrniko** [comment]
@elebelesam 
Hi!

Then Redisson.shutdown method has been executed.

**Comment by elebelesam** [comment]
Hi,

I have shared the same Redisson instance across the threads. It worked as expected.

Thanks.
