### ISSUE TITLE
getBlockingQueue throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by lolandkidtress** [mrniko/redisson#487]
Hi:
when I was using getBlockingQueue method.

following exception happened to me:
[nioEventLoopGroup-2-4] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(2) exceeds writerIndex(1): SlicedAbstractByteBuf(ridx: 0, widx: 1, cap: 1/1, unwrapped: UnpooledUnsafeDirectByteBuf(ridx: 11, widx: 464, cap: 496))
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:431)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(2) exceeds writerIndex(1): SlicedAbstractByteBuf(ridx: 0, widx: 1, cap: 1/1, unwrapped: UnpooledUnsafeDirectByteBuf(ridx: 11, widx: 464, cap: 496))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1178)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1172)
	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:758)
	at org.redisson.client.protocol.decoder.KeyValueObjectDecoder.decode(KeyValueObjectDecoder.java:30)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:217)
	at org.redisson.client.handler.CommandDecoder.decodeMulti(CommandDecoder.java:239)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:229)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:108)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:376)
	... 18 more

and this exception will double the connection numbers with redis server.

my env:
Redis 3.0.2
Redisson 2.2.11
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Java code looks like this:

package com.James.redis_failover_client;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;
import org.redisson.Config;
import org.redisson.Redisson;
import org.redisson.RedissonClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Random;
import java.util.concurrent.TimeUnit;

/**
 * Unit test for simple App.
 */
public class blpopTest extends TestCase {

    private static final Logger logger = LoggerFactory.getLogger(blpopTest.class.getName());

    public static RedissonClient rclient;

    private static final String value = "keyorg_token_tracker_385b678b153d44beba0eb72746e72f02," +
            " value:{\"token\":\"385b678b153d44beba0eb72746e72f02\",\"job_paths\":{},\"emptyRpt\":0,\"RptRequird\":\"true\",   " +
            "\"org_account\":\"qufenqi\",\"RawdataRequird\":\"false\",\"Category\":\"\",\"RptVer\":\"4.0\"," +
            "\"RptType\":\"token\",\"AwsNum\":0,\"Aws\":[],\"CompleteTask\":[],\"interfaceSucTask\":[],\"RptNum\":0," +
            "\"TkStatus\":\"未开始\",\"accounts\":[],\"ver\":0,\"InterfaceDBStatus\":{}}" ;

    public blpopTest(){
        rclient = getPool();
    }
    /**
     * Create the test case
     *
     * @param testName name of the test case
     */
    public blpopTest(String testName)
    {
        super( testName );
    }

    /**
     * @return the suite of tests being tested
     */
    public static Test suite()
    {
        return new TestSuite( blpopTest.class );
    }

    /**
     * Rigourous Test :-)
     */
    public void testApp()
    {
        assertTrue( true );
    }

    public static void main(String[] args) throws Exception {
        try {

//            RedisClient.INSTATNCE.initRandomMode("127.0.0.1@6380@foobared,127.0.0.1@6379",9093);
//            RedisClient.INSTATNCE.initRandomMode("127.0.0.1@6380@foobared",9093);
            new blpopTest();
            while(true){
                int ran = new Random().nextInt(1000);
                rclient.getBlockingQueue(String.valueOf(ran)).add(value);
                rclient.getBlockingQueue(String.valueOf(ran)).expire(1, TimeUnit.SECONDS);
                rclient.getBlockingQueue(String.valueOf(ran)).poll(1, TimeUnit.SECONDS);
            }

        }catch(Exception e){
            e.printStackTrace();

        }

    }

    private RedissonClient getPool(){
        String password = "foobared";
        String redis_ip ="127.0.0.1";
        String redis_port="6380";
        Config config = new Config();

        if(password!=null&&!password.isEmpty()){
            config.useSingleServer().setAddress(redis_ip.concat(":").concat(String.valueOf(redis_port)))
                    .setPassword(password)
                    .setIdleConnectionTimeout(5000)
                    .setConnectionMinimumIdleSize(20)
                    .setTimeout(3000).setFailedAttempts(5)
                    .setRetryAttempts(5).setClientName("name");

        }else{
            config.useSingleServer().setAddress(redis_ip.concat(":").concat(String.valueOf(redis_port)))
                    .setIdleConnectionTimeout(5000)
                    .setConnectionMinimumIdleSize(20)
                    .setTimeout(3000).setFailedAttempts(5)
                    .setClientName("name");
        }

        rclient = Redisson.create(config);
        return rclient;
    }
}

**Comment by lolandkidtress** [comment]
sorry,connection numbers is my miss,
please ignore it

**Comment by mrniko** [comment]
Could you please provide a testcase to reproduce this bug?

**Comment by lolandkidtress** [comment]
[blpopTest.java.zip](https://github.com/mrniko/redisson/files/262450/blpopTest.java.zip)

sample code looks like this.

**Comment by mrniko** [comment]
Fixed
