### ISSUE TITLE
redis master/slaver switch exception

### ISSUE THREAD

**Issue by mz02606046** [mrniko/redisson#517]
When redis master-slave switch,my project throw exception.

org.redisson.client.RedisTimeoutException: Redis server response timeout (10000 ms) occured for command: (EVAL) with params: [if (redis.call('exists', KEYS[1]) == 0) then redis.call('hset', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; if (redis.call('hexists', KEYS[1], ARGV[2]) == 1) then redis.call('hincrby', KEYS[1], ARGV[2], 1); redis.call('pexpire', KEYS[1], ARGV[1]); return nil; end; return redis.call('pttl', KEYS[1]);, 1, carreport:triggerTasklock, 60000, ac3e8c0c-ae1c-4e4f-8276-fb521dfb9db2:59] channel: [id: 0x4b899b90, /172.31.11.194:53918 => /172.31.11.129:7001]
        at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:475) ~[redisson-2.2.8.jar:na]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.0.34.Final.jar:4.0.34.Final]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.0.34.Final.jar:4.0.34.Final]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.0.34.Final.jar:4.0.34.Final]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_60]

I ues redisson 2.2.8 and cluster mode.

Thank you very much.

--Marck

**Comment by mrniko** [comment]
Hi!

There was a couple of bugs in master/slave switch handling in cluster mode. Those bugs were fixed in 2.2.12 version. So I suggest you to update Redisson version and check it again.

**Comment by mz02606046** [comment]
Thanks for you.Answer my question so fast.
This question is solved.

I have another question.In the two redis clusters. one has a problem.
redisson request will throw an exception.server respones timeout.
the other one no problem.
 
I want to know whether this is related to redis cluster configuration.

**Comment by mrniko** [comment]
@mz02606046 
> server respones timeout

First, you need to know what cause the response timeout (network, too high cpu load, etc...)
