### ISSUE TITLE
Connection pool exhausted

### ISSUE THREAD

**Issue by pengfei-xu** [mrniko/redisson#550]
I met similar problem these days online  used  of sub/pub.  
org.redisson.client.RedisConnectionException: Connection pool exhausted!  Disconnected hosts: [10.25.63.47/10.25.63.47:7091]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:169) ~[redisson-2.2.17.jar:na]
	at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:25) ~[redisson-2.2.17.jar:na]
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:371) ~[redisson-2.2.17.jar:na]
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:600) ~[redisson-2.2.17.jar:na]
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:401) ~[redisson-2.2.17.jar:na]
	at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:450) ~[redisson-2.2.17.jar:na]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581) ~[netty-common-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655) ~[netty-common-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367) ~[netty-common-4.1.0.Final.jar:4.1.0.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_65]

The version I use is 2.2.17, I have 2 redis server, one master and one slave, in sentinel mode. It is in test environment so net work and cpu usage is low.
This error appears about every 1 day.

**Comment by mrniko** [comment]
Have you tried to increase connection pool size?

**Comment by pengfei-xu** [comment]
i tried it but no effect .  i distrust connection pool  release  Invalid connection

**Comment by mrniko** [comment]
Invalid connections are always return back to pool. You can switch on log level to `trace` and see it by yourself.

**Comment by mrniko** [comment]
As I see from your trace problem occurs during write operation (not pub/sub command) on master node. Have you checked connection with 10.25.63.47:7091?

**Comment by mrniko** [comment]
Do you see disconnected due to failedAttempts substring in logs?

**Comment by pengfei-xu** [comment]
I use useSentinelServers.  when  Someone  switching Master slave  , will cause it .
2016-07-14 15:37:55.926 WARN  o.r.c.SentinelConnectionManager.slaveDown:285 slave: 10.161.230.196:7091 has down

2016-07-14 15:37:55.926 WARN  o.r.c.SentinelConnectionManager.slaveDown:285 slave: 10.161.230.196:7091 has down

2016-07-14 15:37:56.084 WARN  o.r.c.SentinelConnectionManager.onNodeDown:272 master: 10.161.230.196:7091 has down

2016-07-14 15:37:56.084 WARN  o.r.c.SentinelConnectionManager.onNodeDown:272 master: 10.161.230.196:7091 has down

2016-07-14 15:37:56.174 WARN  o.r.c.SentinelConnectionManager.slaveDown:285 slave: 10.161.230.196:7091 has down

2016-07-14 15:37:56.174 WARN  o.r.c.SentinelConnectionManager.slaveDown:285 slave: 10.161.230.196:7091 has down

**Comment by mrniko** [comment]
Does 10.161.230.196:7091 slave became a master?

**Comment by pengfei-xu** [comment]
NO  it is  10.161.230.196 -> 10.168.77.146

**Comment by mrniko** [comment]
> NO it is 10.161.230.196 -> 10.168.77.146 

Sorry I didn't understand you. Do you shutdown 10.161.230.196 right? and then 10.168.77.146 node became a master? How many slaves do you have?

**Comment by pengfei-xu** [comment]
yes  shutdown 10.161.230.196 right   and then 10.168.77.146 node became a master   I have  one slave

**Comment by mrniko** [comment]
If you don't want to get command execution exceptions during master node migration you can increase `retryAttempts` setting

**Comment by pengfei-xu** [comment]
I mean it do not auto switch  10.168.77.146 node became a master . always  retryAttempts master 10.161.230.196 r

**Comment by mrniko** [comment]
Can't reproduce this bug with 2.2.20 version.

Here is my test:
```java
        Config config = new Config();
        config.useSentinelServers()
                .setMasterName("mymaster")
                .addSentinelAddress("127.0.0.1:26389", "127.0.0.1:26379", "127.0.0.1:26399")
                .setRetryAttempts(100);
        
        RedissonClient r = Redisson.create(config);
        RTopic<Object> topic = r.getTopic("1234");
        topic.addListener(new MessageListener<Object>() {
            
            @Override
            public void onMessage(String channel, Object msg) {
                System.out.println("received message: " + msg);
            }
        });
        
        Thread t = new Thread() {
            public void run() {
                for (int i = 0; i < 100; i++) {
                    r.getTopic("1234").publish("" + i);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            };
        };
        t.start();
        
        t.join();
```java

**Comment by pengfei-xu** [comment]
you mean when switch Master slave , I increase retryAttempts setting to switch end . how much retryAttempts it is right

**Comment by mrniko** [comment]
> you mean when switch Master slave 
Yes.
You can increase `retryAttempts` either `retryInterval` . Try retryAttempts=25
