### ISSUE TITLE
can't find slaves

### ISSUE THREAD

**Issue by mz02606046** [mrniko/redisson#593]
My program in the process of running.Occasionally, there will be no node to find!

2016-08-25 03:49:46.088 [nioEventLoopGroup-2-1] WARN  io.netty.util.concurrent.DefaultPromise - An exception was thrown by org.redisson.cluster.ClusterConnectionManager$5.operationComplete()
java.lang.IllegalStateException: Can't find /172.31.11.129:7001 in slaves!
        at org.redisson.connection.balancer.LoadBalancerManagerImpl.unfreeze(LoadBalancerManagerImpl.java:79) ~[redisson-2.2.14.jar:na]
        at org.redisson.connection.MasterSlaveEntry.slaveUp(MasterSlaveEntry.java:297) ~[redisson-2.2.14.jar:na]
        at org.redisson.cluster.ClusterConnectionManager.upDownSlaves(ClusterConnectionManager.java:365) ~[redisson-2.2.14.jar:na]
        at org.redisson.cluster.ClusterConnectionManager.checkSlaveNodesChange(ClusterConnectionManager.java:353) ~[redisson-2.2.14.jar:na]
        at org.redisson.cluster.ClusterConnectionManager.access$1300(ClusterConnectionManager.java:54) ~[redisson-2.2.14.jar:na]
        at org.redisson.cluster.ClusterConnectionManager$5.operationComplete(ClusterConnectionManager.java:335) ~[redisson-2.2.14.jar:na]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683) [netty-common-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:604) [netty-common-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:564) [netty-common-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:407) [netty-common-4.0.36.Final.jar:4.0.36.Final]
        at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:348) [redisson-2.2.14.jar:na]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:256) [redisson-2.2.14.jar:na]
        at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:114) [redisson-2.2.14.jar:na]
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:376) [netty-codec-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) [netty-codec-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.36.Final.jar:4.0.36.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_60]

my redisson 2.2.14. master/slaver mode . redis cluster 3.x

**Comment by mrniko** [comment]
When does it happen? During application startup?

**Comment by mz02606046** [comment]
When the program is running, it is not starting.

**Comment by mrniko** [comment]
Fixed
