### ISSUE TITLE
java.lang.NoClassDefFoundError: io/netty/channel/epoll/EpollEventLoopGroup

### ISSUE THREAD

**Issue by eimhee** [mrniko/redisson#600]
892 [main] INFO org.redisson.Version - Redisson 2.3.0

java.lang.NoClassDefFoundError: io/netty/channel/epoll/EpollEventLoopGroup

	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:163)
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:154)
	at org.redisson.connection.SingleConnectionManager.<init>(SingleConnectionManager.java:43)
	at org.redisson.config.ConfigSupport.createConnectionManager(ConfigSupport.java:166)
	at org.redisson.Redisson.<init>(Redisson.java:103)
	at org.redisson.Redisson.create(Redisson.java:133)
	at redisson.ConfigTest.connect(ConfigTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.epoll.EpollEventLoopGroup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more

**Comment by mrniko** [comment]
epoll is optional dependency. You should add it to classpath. Here is dependency:

        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.0.40.Final</version>
            <scope>provided</scope>
        </dependency>

**Comment by eimhee** [comment]
thanks, I have added the dependency,  but it only support on linux, how to add a dependency for windows

Caused by: java.lang.IllegalStateException: Only supported on Linux
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:267)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:64)
	... 44 more

**Comment by mrniko** [comment]
windows doesn't have such feature

**Comment by fuatse** [comment]
@eimhee I had the same issue on windows but it was gone when I upgraded my netty-all jar to v4.1.5 https://mvnrepository.com/artifact/io.netty/netty-all/4.1.5.Final

**Comment by SDUmzg** [comment]
`            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-tcnative</artifactId>
                <version>${netty-native.version}</version>
                <classifier>${os.detected.classifier}</classifier>
            </dependency>`
may be solve

**Comment by yizhixiaotaozi** [comment]
anyone can fix this ?

**Comment by jackygurui** [comment]
@yizhixiaotaozi please check you pom.xml and see if you have following dependency decleared
```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <scope>provided</scope>
        </dependency>
```

**Comment by xingxiang** [comment]
in linux you can try

`<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <classifier>linux-x86_64</classifier>
            <version>${netty.version}</version>
        </dependency>`

**Comment by xingxiang** [comment]
in linux you can add <classifier>linux-x86_64</classifier>
