### ISSUE TITLE
Issue with using Executor Service

### ISSUE THREAD

**Issue by jebynot** [mrniko/redisson#602]
I am trying to use Executor Service to do a distribute processing of some records. I started with a basic configuration as follows

```java

@Bean(name="redisonConfig")
	public org.redisson.config.Config redisonConfig() {
		org.redisson.config.Config config = new org.redisson.config.Config();
		config.useElasticacheServers()
				.setScanInterval(2000) // master node change scan interval
				.addNodeAddress("localhost:6379");
		return config;
	}

	@Bean(name="redissonClient")
	@DependsOn("redisonConfig")
	public RedissonClient redissonClient(@Qualifier("redisonConfig") org.redisson.config.Config redisonConfig) {
		RedissonClient redisson = Redisson.create(redisonConfig);
		return redisson;
	}

	@Bean(initMethod="start", destroyMethod = "shutdown")
	public RedissonNode redissonNodeConfig(@Qualifier("redisonConfig") org.redisson.config.Config config) {

		RedissonNodeConfig nodeConfig = new RedissonNodeConfig(config);
		Map<String, Integer> workers = new HashMap<String, Integer>();
		workers.put("contentSaveExecutor", 1);
		nodeConfig.setExecutorServiceThreads(1);
		nodeConfig.setExecutorServiceWorkers(workers);

		RedissonNode node = RedissonNode.create(nodeConfig);

		return node;
	}
```

Here is my Executor Service and Callabable.

```java
List<ContentSaveCallable> contentSaveRunnables = new ArrayList<>();

		contentSaveRunnables.add(new ContentSaveCallable());
		RExecutorService executorService = redissonClient.getExecutorService("contentSaveExecutor");
		List<Future<Long>> futures = null;
		try {
			futures = executorService.invokeAll(contentSaveRunnables);
			for (Future<Long> future : futures) {
				future.get(1500000, TimeUnit.MILLISECONDS);
			}
		} catch (InterruptedException e) {
			e.printStackTrace();
		} catch (ExecutionException e) {
			e.printStackTrace();
		} catch (TimeoutException e) {
			e.printStackTrace();
		}
private class ContentSaveCallable implements Callable<Long>,Serializable {

		Long contentDTOs;

		@RInject
		private RedissonClient redissonClient;

		@Override
		public Long call() {

			System.out.println("Hi");
			return contentDTOs;
		}
	}
```

But I am running into serialization issue with below stacktrace.

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Problem deserializing 'setterless' property ("path"): no way to handle typed deser with setterless yet (through reference chain: org.redisson.remote.RemoteServiceResponse["error"])
	at com.fasterxml.jackson.databind.deser.impl.SetterlessProperty.deserializeAndSet(SetterlessProperty.java:102)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:134)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:122)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:993)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:518)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:134)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:122)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:993)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:518)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:134)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:122)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:165)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:550)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:42)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2784)
	at org.redisson.codec.JsonJacksonCodec$2.decode(JsonJacksonCodec.java:74)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:270)
	at org.redisson.client.handler.CommandDecoder.decodeList(CommandDecoder.java:299)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:289)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:117)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
`

**Comment by mrniko** [comment]
`ContentSaveCallable` is a private class

**Comment by jebynot** [comment]
thank you Nikita.I will correct and test
