### ISSUE TITLE
MasterConnectionPool exhausted!  Hosts with fully busy connections

### ISSUE THREAD

**Issue by davidtinker** [mrniko/redisson#615]
I am using a RScheduledExecutorService as a job queue backed by a java ThreadPoolExecutor:

    executor = redisson.getExecutorService("pickle:feed-reader-executor")
    pool = new ThreadPoolExecutor(numThreads, numThreads, 0L, TimeUnit.MILLISECONDS,
                new LinkedBlockingQueue<Runnable>(), new NamedThreadFactory("feed-reader"))
    executor.registerWorkers(32, pool)

Other code schedules jobs on the executor. The problem I have is that after a while if the service is busy it eventually runs out of connections. 

    Caused by: org.redisson.client.RedisConnectionException: MasterConnectionPool exhausted!  Hosts with fully busy connections: [/127.0.0.1:6379]
	at org.redisson.connection.pool.ConnectionPool.get(ConnectionPool.java:165)
	at org.redisson.connection.pool.MasterConnectionPool.get(MasterConnectionPool.java:25)
	at org.redisson.connection.MasterSlaveEntry.connectionWriteOp(MasterSlaveEntry.java:361)
	at org.redisson.connection.MasterSlaveConnectionManager.connectionWriteOp(MasterSlaveConnectionManager.java:621)
	at org.redisson.command.CommandAsyncService.async(CommandAsyncService.java:435)
	at org.redisson.command.CommandAsyncService$7.run(CommandAsyncService.java:484)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:588)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:662)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:385)

I added some hackery to get info on the number of free connections and print this periodically:

    [freeSubscribeConnectionsAmount=0, freeSubscribeConnectionsCounter=49, freeConnectionsAmount=1, freeConnectionsCounter=1977, freezed=false, freezeReason=null, client=[addr=/127.0.0.1:6379], nodeType=MASTER, failedAttempts=0]

The freeConnectionsCounter + freeConnectionsAmount value started dropping as more and more requests are executed. It doesn't drop one-for-one with requests so at least some of the time connections are being released. Interesting if the server gets less busy for a while before running out of connections then suddenly a bunch get released and things recover.

Any idea whats going on here and how I can fix this? Tx.

**Comment by mrniko** [comment]
`freeConnectionsAmount` could be lower than `freeConnectionsCounter` in case when acquired connection is not alive or disconnected and can't be return to connection pool. In this case only `freeConnectionCounter` will be increased.

Do you see such messages in your log `disconnected due to failedAttempts` ?

**Comment by davidtinker** [comment]
I set logging for org.redisson to WARN and this is what ends up in the log:

    2016-09-14 09:17:37.202    WARN feed-reader-3-t31 MasterConnectionPool: host /127.0.0.1:6379 disconnected due to failedAttempts=3 limit reached
    2016-09-14 09:19:04.100    WARN nioEventLoopGroup-2-1 MasterConnectionPool: host /127.0.0.1:6379 disconnected due to failedAttempts=3 limit reached
    2016-09-14 09:19:07.998   ERROR feed-reader-3-t30 FeedSchedulerService: Error scheduling read for BETF17AA:14585: org.redisson.client.RedisConnectionException: MasterConnectionPool exhausted!  Disconnected hosts: [/127.0.0.1:6379]

The tasks I am running basically do this:

    // schedule this task to run again soon in case something goes wrong
    String safetyTaskId = executor.scheduleAsync(..., some point in the near future)
    .. do work ...
    // figure out when the task needs to run again and cancel the 'safety' task
    executor.cancelScheduledTask(safetyTaskId)
    executor.scheduleAsync(..., correct time to run)

If I leave out the 'safety' task scheduling and cancellation then I don't have connection issues.

I was thinking of dropping the RScheduledExecutorService and just polling a RScoredSortedSet holding 'next run time' info for my tasks. I don't need this to run on multiple machines or anything.

**Comment by mrniko** [comment]
As I suspected you have some kind of network problems due to presence of `disconnected due to failedAttempts` messages. This message occurs when acquired connection from pool or just established connection is disconnected. After 3 failed attempts Redisson removes such node from pool and tries to reconnect to it every `reconnectionTimeout` interval. If it became available then Redisson returns it back.

**Comment by davidtinker** [comment]
I worked around whatever the issue is by polling a RScoredSortedSet instead of using a RScheduledExecutorService. Tx for the excellent library.

**Comment by mrniko** [comment]
This issue resolved here https://github.com/redisson/redisson/issues/680
